### ISSUE TITLE
Step 3 (pre-processing audit check) of FVS Output Load produces an audit summary page requiring a vertical scroll bar

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#100]
When running step 3 on multiple packages (and variants), you get an audit results summary page at the end that, in today's case, had instances of a message telling me that  "tree cut more than once for a single package for variant/package BM/009 (See audit table audit_fvs_tree_id_cut)" for every package-- as there were 33 packages, this did not fit on the monitor and so much of the text was off screen and not reachable because there is no vertical scrollbar on this display window.

**Comment by lbross** [comment]
The current implementation uses a MessageBox to show the audit results which does not support scrollbars. Will switch this to a textbox like we use for Processor Scenario properties that does have a scrollbar.

**Comment by lbross** [comment]
I created a new uc called uc_textboxWithButtons.cs that is similar to uc_textbox.cs except it has a close button at the bottom like a MessageBox. This uc could be used in other places where a MessageBox isn't big enough. I used the new uc in uc_fvs_output.RunPREAudit_Main() aka Step 3 (pre-processing audit check) of FVS Output Load.

This will be in the next release of BioSum.

**Comment by lbross** [comment]
Validated in 5.7.9. Closing per @jsfried.
