### ISSUE TITLE
FVS: FVS created trees with spcd 298/998/999 have null drybiot

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#102]
Originally reported by @carlinstarrs under variant WS. @jsfried also experienced problem with BM. These FVS codes are not recognized in FIA. @jsfried requests the following:

Suggest modifying the code so that the volume calculations done at FVS OUTPUT LOAD time for trees coded 298 pass species 299 to the FCS algorithm (but don’t change the species code on the tree, because processor will need to look it up as a 298 in the tree_species table when figuring density, etc.). Along the same lines, trees with SPCD 999 should have their volume and biomass evaluated as if they were 998 (because the current FCS code does support that—see below).
 
Another part could be that the outdated version of FCS we are still using might not contain algorithms for calculating biomass and volume of trees with species code 998 (other hardwood, which is a valid FIA code, at least for dead trees). Clearly the current version of FCS in NIMS does, because there are trees with this species code (generally dead ones) in FIADB with volumes and biomass values.
 
I see it as kind of important that we close the loop on this (updating to the current FCS to process the 998 tree and 999 trees recasted as 998 and recasting the 298s as 299s for vol and biomass calc purposes) for the sake of completeness and because zeros are not good values to have. Not only, will there be no revenue and volume produced (which I am less worried about) but the treatments will come up as very low cost (because the volume and mass of the trees comes in as zero, OpCost thinks there isn’t much material to be removed). To summarize:
 
FVS code              Calc DRYBIOT etc. using new FCS as if
298                       299
999                       998
998                       998

**Comment by lbross** [comment]
We discussed this issue on our DEV call today. @lpotts asked if the cut list should contain the original or FIA species code? For example: 298 or 299?

I will look into the following questions regarding downstream effects on Processor.

1. How is the spcd assigned by Processor for FVS-created trees? There is a separate path
2. How are the species codes extracted for the species groups screen? For example: if we leave the spcd as 298 will it be included in a species group?
3. Where is the dry-to-green value pulled from in Processor if the species (298) is not on the tree_species table?

The answers to these questions will allow us to make an educated decision about which spcd to use in the cut list.

**Comment by lbross** [comment]
Answers to a couple of these questions.

1. If a tree is created by FVS, Processor assigns the spcd in the fvs_species column in the cut list. If a tree is not created by FVS, it assigns the spcd from the tree table, linking on the fvs_tree_id.

3. Processor pulls dry-to-green from the tree_species table linking on the spcd assigned in item 1. If the spcd/variant is not in the tree_species table, Processor puts up a warning and stops processing. If we retain 298 and 999 we would have to add these to the tree_species table (or its upcoming replacement) for all variants.

**Comment by lbross** [comment]
After reviewing the processor code, I believe the following changes would be necessary if we want to maintain spcd 298 and 999 through the system to processor. Per our discussion, these are not valid FIA spcd so BioSum doesn't fully support them.
1. These spcd need to be added to the tree_species table for all relevant variants. This is the source of od_wgt, etc for Processor. Also the source for common_name which is used on the tree species groups screen.
2. A code change needs to be made on the tree species groups screen to identify spcd for FVS-created trees in the cut list that are not in the tree table. The * denoting "trees found in the FVS tree tables" depends on tree spcd existing in the tree table. If there aren't any trees in the tree table with a spcd, that species will not be marked with an "*". This could be the case with FVS-created trees. This SQL gathers the species to mark with an "*":
SELECT DISTINCT t.spcd,f.fvs_variant 
INTO tree_spc_groups_temp 
FROM tree t, fvsouttreetemp f 
WHERE f.fvs_tree_id = t.fvs_tree_id
I propose adding another query that gathers the spcd variants from the cut list for FVS-created trees to mark these species with an "*" if they were missing from the initial query.

If we do not make these changes but do send through trees under spcd 298 and 999, Processor will catch it and error out. Processor checks to make sure the spcd exists on the tree_species table. It also checks to make sure every spcd in use has a species group.

Hope that @lpotts  can review my suggestions before we make a final decision.

**Comment by lbross** [comment]
Archiving my notes from research. No need to review unless desired.
Species Groups:
Needs to be present in tree_species table

// For Each cut list (cut list includes FVS-created trees)
// Note: fvs_species not necessarily spcd; Look back to tree table for non-FVS created trees
INSERT INTO fvsouttreetemp2 (fvs_tree_id,fvs_variant,fvs_species) 
SELECT DISTINCT fvs_tree_id,fvs_variant,fvs_species 
FROM fvs_tree_IN_BM_P002_TREE_CUTLIST

SELECT DISTINCT * INTO fvsouttreetemp FROM fvsouttreetemp2

//Get list of common_name from tree_species table
Query1


//Get list of spcd, common_name from tree_species table
Query2
298 not here, 998 (other), 999 (Unknown) are (not in all variants)

// Must exist in both tree table and cut list; We may be excluding spcd for FVS created not in tree table
SELECT DISTINCT t.spcd,f.fvs_variant 
INTO tree_spc_groups_temp 
FROM tree t, fvsouttreetemp f 
WHERE f.fvs_tree_id = t.fvs_tree_id
Here we lose 298, 998, and 999 because not in tree table

// Must exist in tree species table and tree_spc_groups_temp
SELECT DISTINCT s.common_name
FROM tree_spc_groups_temp t, tree_species s
WHERE t.spcd = s.spcd AND
TRIM(UCASE(t.fvs_variant)) = TRIM(UCASE(s.fvs_variant))

**Comment by lbross** [comment]
Add logic to uc_processor_scenario_tree_spc_groups.loadvalues()

- Add  FvsCreatedTree_YN field to query generated by Queries.Processor.AuditFvsOut_SelectIntoUnionOfFVSTreeTablesUsingListArray
- // New query to get common_name for fvs created trees not on the tree table
SELECT DISTINCT s.common_name
FROM fvsouttreetemp t, tree_species s
WHERE val(t.fvs_species) = val(s.spcd) AND
t.FvsCreatedTree_YN = 'Y' AND
TRIM(UCASE(t.fvs_variant)) = TRIM(UCASE(s.fvs_variant))
- Loop through the query results setting FVSOutput to true for all common names found in the query results. Copy what we are already doing for the output of the tree/fvs output join

**Comment by lbross** [comment]
Found that tree species groups screen was taking TOO long to load. The new query to get the common_name for fvs created trees not on the tree table was the culprit. Removed the val() function from s.spcd because it is already a number. Performance is back within acceptable time frame.

```
SELECT DISTINCT s.common_name FROM fvsouttreetemp t, tree_species s
WHERE t.FvsCreatedTree_YN = 'Y'
AND val(t.fvs_species) = s.spcd 
AND TRIM(UCASE(t.fvs_variant)) = TRIM(UCASE(s.fvs_variant))
```

**Comment by lpotts** [comment]
The fvs_tree.fvs_species column is a text field so it is using the VAL( function to convert the text to numeric in order to compare with the numeric TREE_SPECIES.SPCD column.

**Comment by lbross** [comment]
Thanks @lpotts. Yes. I left the val(fvs_tree.fvs_species) in the query for the reason you outlined above. However, for some reason, I also had it on TREE_SPECIES.SPCD where we do NOT need it because TREE_SPECIES.SPCD is already a number. This small change improved performance a great deal and still gave the correct result.

**Comment by jsfried** [comment]
Another place to look for performance improvement is in the species group definitions-- that screen takes many minutes to come up, even in the Blue Demo project (that isn't all that big).

**Comment by lbross** [comment]
@jsfried: I think you may be referring to what I fixed this afternoon. Are you talking about the screen that loads when you click the 'tree species groups' buttons from the Tree Groupings screen in Processor? This was taking FOREVER to load due to some SQL that I just fixed. The slowness was introduced in 5.8.0 but will be better in the next .msi.

**Comment by jsfried** [comment]
I inserted an ES tree of species 998 into the CUTLIST for the FTCE Mid project BM package 9 to test for the fix of issue #102. Unfortunately, Issue #102 appears not to be fixed because this inserted tree does not get populated with volume and biomass, generating an error in the OUTPUT load audit. I will post the project for Lesley to confirm this.

**Comment by lbross** [comment]
@jsfried: I believe you have to add the test tree earlier in the process to validate the volume and biomass values. The code to populate the volume and biomass runs when processing the FVS output. If you manually populate the output and biomass, you can verify that the rest of our fixes work. That is, that the species shows up on the tree species group screen with an asterisk and that the tree doesn't cause processor errors. Remember that the tree species group screen takes a super long time to load right now but this will be fixed in the next .msi.

@lpotts: Please let us know if I'm wrong.

**Comment by jsfried** [comment]
@lbross: I am now very confused. We are validating at the FVS OUTPUT LOAD stage, NOT PROCESSOR. I added the ES tree w spcd 998 in the CUTLIST table in FVSOUT_BM_P009-900-000-000-000.MDB file that emerges from FVS. I don't see how I could have placed it any earlier than that. It is tree ID ES423028 and can be found in the zip at https://usfs.box.com/s/8nro23boncne6sbwo1unnnk3u5v2u62a . The tree species groups screen doesn't happen until processor, and with new tree_species table, I did find that new species showed up in the tree_species_groups screen, though I don't think there were any 998s at that point. I can try testing that. But we do need to find out why 998 ES trees don't get DRYBIOT etc assignments.

**Comment by lbross** [comment]
I'm unsure of the exact steps but the biomass and volume info are calculated when the cut list is created. Adding a tree to the cut list after the fact won't cause those values to be populated. I would expect Processor to crash because of the missing values.

This issue was originally raised when @carlinstarrs was trying to load plots in WS at the end of September and had a number of trees coming out of FVS as 298. See e-mail titled 'what to do about this?' Perhaps a better test would be to reload the plots from that project and see if the biomass and volume info are calculated? Unfortunately I can't find a record of what project it was.

**Comment by jsfried** [comment]
I think we are having a communication challenge. If I understand things correctly, there are two cut lists-- the one that FVS produces (e.g., FVSOUT_BM_P009-900-000-000-000.MDB in the \fvs\data\bm folder) and the one that BIOSUM produces (e.g., FVS_TREE in G:\FTCE\Mid\fvs\data\BM\BiosumCalc\BM_P009_TREE_CUTLIST.MDB). I am adding the establishment (ES) tree in the former and expecting it to have its volume and biomass calculated in the latter, but it is not happening. @lpotts: is there some reason why adding an ES tree (w spcd 998) to the cut list in FVSOUT_BM_P009-900-000-000-000.MDB would not be sufficient to get that tree propagated through to the FVS_TREE version of the cutlist in BioSumCalc? I created it by taking an existing tree, then changing the tree number to a number that did not exist in the CUTLIST or MASTER.TREE and putting the ES in front of it.

**Comment by lpotts** [comment]
I successfully tested the conversion of 298 to 299 and
999 to 998 and then calculating volume and biomass.

Have you tried using the troubleshooter to see what volumes and biomass are returned?

Below is the sql that is pretty straight forward in the conversion of the species BEFORE it is sent to oracle for the calculation.

//
//SWAP FVS-ONLY SPECIES CODES TO FIA SPECIES CODES IN ORDER FOR FIA TO CALCULATE VOLUMES
//
//check if original spcd column exists
//save the original spcd
//update the FVS_SPECIES with FIA SPCD for 298,999 trees
   oAdo.m_strSQL = "UPDATE " + strFvsTreeTable + " " +
                 "SET FVS_SPECIES = IIF(FVS_SPECIES='298','299'," +
                                  "IIF(FVS_SPECIES='999','998',FVS_SPECIES)) " +
               "WHERE FVS_SPECIES IN ('298','999')";
                               }

**Comment by jsfried** [comment]
During testing, I discovered that the tree species audit is checking all trees regardless of status, including a status=0 tree that has a species of 542 (Oregon ash) that is not supported in BM. It is the only 542 in master.tree. We should probably only be checking status=1 since those are the only trees addressed in BioSum. @lbross: can we limit what gets checked?

**Comment by jsfried** [comment]
I tried to add the species 542 via the checkbox and it does add it but then does not let me edit it to tell it which species to crosswalk it to (I would like it to go to 998)

![image](https://user-images.githubusercontent.com/17485472/35950742-d0082990-0c2c-11e8-8821-840986554748.png)

However, I am able to add the record manually, typing in all the fields in the dialog.

**Comment by jsfried** [comment]
I re-tested Blue Mountains Demo 10 (which Loaded package 29 fine earlier this afternoon with no added records in the cut list). This time, I changed a dead tree in master.tree to live and changed its species code to 298 and added it and another 298 (with an ES Tree ID) in the Cutlist and tried to run step 3. I got this in return:

![image](https://user-images.githubusercontent.com/17485472/35950912-b9a23334-0c2d-11e8-8592-b594823bd942.png)

![image](https://user-images.githubusercontent.com/17485472/35950922-c47dc11a-0c2d-11e8-9606-e10e474162ea.png)

![image](https://user-images.githubusercontent.com/17485472/35950930-d04590cc-0c2d-11e8-965a-1746b74b24fc.png)

I continued on to step 4 and 5. When I checked the records for these two added trees in BioSum Calc Cutlist database, the ES record was populated with volume and biomass information whereas the existing record (the one in MASTER.TREE that I changed from dead to live and changed species to 298), was not.

**Comment by carlinstarrs** [comment]
I tested this with a version of the CEC project that had previously yielded null values that were keeping processor from running. I re-ran the FVS OUTPUT module steps and checked for null drybiot values in the BiosumCalc Cutlist files and did not find any. I checked these against values that were null in the previous version of the project and they now had values. 

However, when I go to run processor, I'm still getting the "tree_species table is missing either an entry or species group for variant/spcd x" even though every tree species audit I can run passes and they don't show in the processor/rule definitions/tree grouping/tree species as a * species. Previously I was able to fix this by adding the spcd to the scenario_processor_rule_definitions tree_species_groups_list. 

Some of these species are ones I had to add before running FVS based on the initial audit results in the FVS module not knowing how to map them, so those may not be an issue anymore with the new tree_species table (and I probably did it wrong), but I was also getting it for WS 298. In that case adding it to the scenario_processor_rule_definitions tree_species_groups_list did fix it.

**Comment by lbross** [comment]
@carlinstarrs: Can you post the project with the tree_species errors? I'd like to take a look before we dismiss it, just to be safe. No rush.

**Comment by carlinstarrs** [comment]
https://usfs.box.com/s/jzj0v923mw7pks0y5ldq2hy4jrbwel84

**Comment by lbross** [comment]
@carlinstarrs: just sent an e-mail on the species group stuff. After that, I ran into a new problem with CA 014. There are about 13 seedlings in the FVS_tree cut list where voltsgrs is null which causes processor to crash. They are all spcd 818. I'm not clear on whether you were able to get all the packages through the FVS OUTPUT module steps? Or if these are results from an older BioSum version?

Also, I have a vague recollection that we shouldn't be sending seedlings to FVS but am not sure. This may be an artifact from an old project.

**Comment by jsfried** [comment]
Seedlings may be sent to FVS for use in REPUTE parameterization. However, they should not be on any cut list until they are over 1 inch in diameter at breast height and thus able to have volume and biomass estimated. Seedlings are evident as DIA=0.1-- are you seeing these in FVS output?

**Comment by lpotts** [comment]
Is it an FVS CREATED tree?

**Comment by lbross** [comment]
These are FVS CREATED trees. The dbh for all the trees is 0.1. They are showing up in the CEC project Carlin posted yesterday in \fvs\data\CA\BiosumCalc\CA_P014_TREE_CUTLIST.MDB.

**Comment by jsfried** [comment]
Seedlings are something we want FVS to know about. BioSum does not need to know about them, even if they are on cut lists-- there is no costing on their removal, and no volume. They should be purged from FVS output when it is read in from the FVSOUT databases. It is important for the to be on the cut list if they are assumed removed (e.g., by driving over them with equipment) so that they don't spring up and generate new ladder fuels when stands are projected forward.

**Comment by lbross** [comment]
I can update the query that selects the trees for Processor to exclude trees where dbh < 1.0. Or we can update the Post FVS processing to not write these trees to the cut list in the BiosumCalc directory. What is your preference?

**Comment by lpotts** [comment]
My preference is to purge them from the biosumcalc fvs_tree table before doing the biomass/volume calculations.

**Comment by lbross** [comment]
Opened issue #141 and issue #143 to track issues that were uncovered tangentially during validation. The original issue has been resolved and validated!

**Comment by jsfried** [comment]
I concur with Larry-- there is not a particularly compelling reason to retain them in the BioSum Calc table.

**Comment by carlinstarrs** [comment]
It took about 1:20 for the Tree Species Groups window to open (under processor) for the CEC project, not sure if that's too long or not
