### ISSUE TITLE
CORE: “Save Rule Definitions” progress bar never shows as complete

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#111]
From @sloreno:
I noticed that the progress bar for “Save Rule Definitions” in the Core Analysis Run window, never turns all yellow, even once the step is complete.

**Comment by lbross** [comment]
This is fixed. Also fixed a spelling error on this line. This will be in the next BioSum release.

**Comment by jsfried** [comment]
Works now.
