### ISSUE TITLE
FVS: Save button disabled on rxPackage edit screen

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#116]
From @jsfried:
I am pretty sure that I raised this before some time, but I am still seeing it in 5.7.9—and I don’t see it in the GitHub notes for 5.8.0. When editing info in the packages screen, for existing packages—say changing the labeling to correct errors, or changing which Rx happen at each cycle, then closing out of the edits, the Save button never activates to allow me to save my changes, so they are lost when I exit the package editing screen. If I add or delete a package, then I do have the save option available to me.

**Comment by lbross** [comment]
Added flag to uc_rx_package_edit.cs to determine if changes are made that can be saved. If this flag is set to true, the save button will be enabled. The save button should only be enabled if a change is made, not if an analyst just looks at the configuration. Validation will be helpful to see if the save button is enabled when appropriate.

**Comment by jsfried** [comment]
Works now.
