### ISSUE TITLE
PROCESSOR: Add edits to scenario id field

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#117]
Some characters are invalid for a scenario name because they not allowed for creating a folder name. Add edits for both processor and core when creating scenarios to trap and reject these characters:

Forward slashes will not work.
Colons will not work.
Backward slashes will not work.
Question marks will not work.
Single and Double quotation marks will not work.
Ampersands will not work.
Equal sign will not work.
^ character will not work.
| sign will not work. (character above \ character on keyboard key. DOS uses it as a PIPE command.)

Also research if there are other fields within BioSum where these edits would be appropriate.

**Comment by lbross** [comment]
Simplifying this and only allowing letters and underscores in scenario names. This still allows flexibility in scenario naming. Applying this same logic to supplemental harvest cost names

**Comment by jsfried** [comment]
verified
