### ISSUE TITLE
PROCESSOR: Additional harvest costs not summing to complete_cpa column

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#118]
From @jsfried: It seems that scenario additional harvest costs are not being added in processor. I reran FTCE East after revising the values in pile_burn_cpa (a scenario additional harvest cost column). When I looked at the harvest_costs table that resulted from running Processor, the value of complete_cpa and harvest_cpa was identical in every case, even though the scenario additional harvest costs table had a 250 for some rows and nulls for others.

**Comment by jsfried** [comment]
Works now.
