### ISSUE TITLE
Remove copyright warning

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#128]
BioSum is produced by federal employees and by contractors paid from federal funds, so is automatically, by law, in the public domain. The warning that appears when installing from the MSI is unnecessarily draconian, and toothless, yet potentially off-putting. Please remove it from future msi files that we generated.
![image](https://user-images.githubusercontent.com/17485472/36172970-61084cc0-10bc-11e8-8f26-f47d46347ec1.png)

**Comment by lbross** [comment]
Done. Right-click on Setup project in solution explorer and choose view > user interface. Select 'welcome' from outline that appears. Delete CopyrightWarning property.

**Comment by jsfried** [comment]
Notice successfully removed
