### ISSUE TITLE
FVS: Exclude trees with dbh < 1.0 from biosumcalc fvs_tree table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#143]
before doing the biomass/volume calculations. BioSum does not need to know about them, even if they are on cut lists-- there is no costing on their removal, and no volume. These trees cannot have biomass/volume calculated and nulls in these fields cause Processor to crash. Please let me know if @lpotts or @sorgtyler will be working this issue.

**Comment by sorgtyler** [comment]
I tried tracing through the creation of `fvs_tree` in the BioSumCalc folder. I added `dbh >= 1.0` to the filter, but I don't know how to validate it. 

I tried simply modifying some of the `dbh` values in `cutlist_fia_trees_work_table` before running the insert statement. If I *start with **170 rows*** that end up in `fvs_tree` and set 20 of the `dbh` values in the work table to 0.9, ***158** make it to `fvs_tree` instead*. I expected 150, though. 

I'll retry it by just setting a whole stand's diameters to 0.9 and see what happens. Does my reasoning make sense? Should the `dbh >= 1.0` filter be in both of the queries below? Here's the changed code, but you can look at it in context in my fork's issue_143 branch.

```csharp
private void RunAppend_UpdateFVSTreeTable(...) //uc_fvs_output.cs: 4263-4290
{
    ... 
    //insert into fvs tree table
    oAdo.m_strSQL = "INSERT INTO " + strFvsTreeTable + " " +
                         "(biosum_cond_id, rxpackage,rx,rxcycle,rxyear,fvs_variant, fvs_tree_id," +
                          "cut_leave, fvs_species, tpa, dbh, ht, estht,pctcr,FvsCreatedTree_YN,DateTimeCreated) " +
                            "SELECT a.biosum_cond_id, a.rxpackage,a.rx,a.rxcycle,a.rxyear,a.fvs_variant," +
                                   "a.fvs_tree_id,a.cut_leave, a.fvs_species, a.tpa, a.dbh, a.ht, a.estht,a.pctcr," +
                                   "a.FvsCreatedTree_YN,a.DateTimeCreated  " +
                            "FROM cutlist_fia_trees_work_table a," +
                                "(SELECT standid,year " +
                                 "FROM " + strFVSOutSeqNumMatrixTableLink + " " +
                                 "WHERE CYCLE" + strCycle + "_PRE_YN='Y')  b " +
                            "WHERE TRIM(a.biosum_cond_id)=TRIM(b.standid) AND CINT(a.rxyear)=b.year AND a.dbh >= 1.0";

    if (m_bDebug && frmMain.g_intDebugLevel > 2)
        this.WriteText(m_strDebugFile, "START: " + System.DateTime.Now.ToString() + "\r\n" + oAdo.m_strSQL + "\r\n");
    oAdo.SqlNonQuery(oConn, oAdo.m_strSQL);
    if (m_bDebug && frmMain.g_intDebugLevel > 2)
        this.WriteText(m_strDebugFile, "DONE:" + System.DateTime.Now.ToString() + "\r\n\r\n");

    //insert into fvs tree tcuft table
    oAdo.m_strSQL = "INSERT INTO " + strFvsTreeTCuFtTable + " " +
                         "(biosum_cond_id, rxpackage,rx,rxcycle,rxyear,fvs_variant,fvs_tree_id,TCuFt) " +
                            "SELECT a.biosum_cond_id, a.rxpackage,a.rx,a.rxcycle,a.rxyear,a.fvs_variant," +
                                   "a.fvs_tree_id,a.TCuFt " +
                            "FROM cutlist_fia_trees_work_table a," +
                                "(SELECT standid,year " +
                                 "FROM " + strFVSOutSeqNumMatrixTableLink + " " +
                                 "WHERE CYCLE" + strCycle + "_PRE_YN='Y')  b " +
                            "WHERE TRIM(a.biosum_cond_id)=TRIM(b.standid) AND CINT(a.rxyear)=b.year AND a.dbh >= 1.0";
    ...
}

```

**Comment by lbross** [comment]
At this point, you know more about the post FVS process than I, so I'll defer to Larry on the SQL. For validation, I would start with the project Carlin posted last week, because we know it has the problem. I found 13 trees in the cut list in the BioSumCalc directory that had dbh < 1.0 and thus caused problems. I would assume that if you run the FVS Output (including your fix) on this variant/package, these trees would disappear? I'm not sure if this is possible test with the changes you made to fvs_tree_id, but you can try.

Link to project on BioSumBox: https://usfs.box.com/s/jzj0v923mw7pks0y5ldq2hy4jrbwel84

**Comment by sorgtyler** [comment]
The branch I'm working on started with the master branch, so it's the old fvs_tree_id. Would you specify which variant/package has the dbh<1.0 problem? I didn't see it when I picked random variant/package combinations.

**Comment by lbross** [comment]
CA 014. You will see it in \slim_CEC_20180308_5.8.0test\fvs\data\CA\BiosumCalc\CA_P014_TREE_CUTLIST.MDB

**Comment by sorgtyler** [comment]
For reference, I think there's only one stand with dbh < 1.0 in that cutlist, which is 1200706050709300907240001.

**Comment by sorgtyler** [comment]
Adding Larry's response here:
This sql needs the filter:
```csharp
//
//FVS CREATED SEEDLING TREES
//
//make sure there are records to insert
     oAdo.m_strSQL = "SELECT COUNT(*) FROM " +
                  "(SELECT TOP 1 c.standid " +
                   "FROM " + strCasesTable + " c," + strFVSOutTableLink + " t " +
                  "WHERE c.CaseID = t.CaseID AND MID(t.treeid, 1, 2) = 'ES')";
```

Any inserts into this table need the filter:
`cutlist_fvs_created_seedlings_work_table`

This sql needs the filter:
```csharp
//
//FVS CREATED COMPACT TREES
//
//make sure there are records to insert
oAdo.m_strSQL = "SELECT COUNT(*) FROM " +
                  "(SELECT TOP 1 c.standid " +
                   "FROM " + strCasesTable + " c," + strFVSOutTableLink + " t " +
                  "WHERE c.CaseID = t.CaseID AND MID(t.treeid, 1, 2) = 'CM')";
```
Any inserts into this table need the filter.
`cutlist_fvs_created_compacted_work_table`

**Comment by sorgtyler** [comment]
- I ran just that stand (1200706050709300907240001) through FVS.
- I used Carlin's KCP files, but FVS didn't generate an FVS_CUTLIST table. 
- In `uc_fvs_output.val_data()`, `strCutListCount == ""`.
- So, when I do the append step in the FVS Output Data module, the code Larry said to add the `dbh >= 1.0` filter to doesn't even run.

Is there a reason why the cutlist would be empty?

**Comment by carlinstarrs** [comment]
Did it generate the table and it's empty, or it didn't generate the table at all?

**Comment by sorgtyler** [comment]
@carlinstarrs No table.

**Comment by carlinstarrs** [comment]
If line 76ish in the KCP still has: 
CUTLIST            2

It should be printing a CUTLIST, provided trees are being cut. If trees are not cut as per the prescription, there won't be a CUTLIST table. 

Did you run it with these KCPs as well? If not, you might try adding them and seeing if that fixes it. Make sure to add the FVSOUT_blah KCP first, the next three can be in any order 

![image](https://user-images.githubusercontent.com/12533482/37306738-e13098c8-25f5-11e8-84df-adcb1e4b9b81.png)

[addKCPs.zip](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1804358/addKCPs.zip)

**Comment by sorgtyler** [comment]
I should add that the only modification I made to the Predispose.mdb was setting the "All_Stands" group to "All". Let me know if I'm missing a step.

**Comment by carlinstarrs** [comment]
Might be easier to talk for a sec via phone, do you want to call me? 510 685 4049

**Comment by carlinstarrs** [comment]
Here are the missing CA files that should help: https://usfs.box.com/s/pdg3ag0nxyw4lipr2bjr5vpkcoles3gq 

I also included the latest CEC project documentation, so you can see all the manipulations that are made to the Predispose database in case that's helpful. If you do it from the beginning like that there may be some more files I need to send you, I can't remember, but they should be listed in there. Let me know if you need them.

**Comment by sorgtyler** [comment]
I tested my code on the files Carlin linked, and it looks like adding the dbh filters where Larry specified removes the 50 records with `dbh<1.0` in CA_P014_TREE_CUTLIST.MDB.

**Comment by sorgtyler** [comment]
I was revisiting FVS Input queries and wondered if this is related. I was copying the behavior of the text file version of fvs_input.cs, so `dbh=0.1` implies seedlings. Does issue #143 only concern FVS-created trees?
```csharp
//Old way in fvs_input.cs
dblDbh = Math.Round(dblDbh,1);
if (x==LIVE_TREE)
{
    if (dblTpa > 25 && dblDbh <= 0) dblDbh = 0.1; //assume to be a seedling
}

//Compared to current way in Queries.cs for input database version:

//Set Dbh to 0.1 if Tpa > 25 and dbh <= 0 and live tree (implies seedlings) 
public static string SetInferredSaplingDbh(string strDestTable) //needs to be renamed to SetInferredSaplingDbh
{
    return "UPDATE " + strDestTable + " SET Dbh=0.1 WHERE Tree_Count > 25 AND Dbh <= 0 AND History=1;";
}
```

**Comment by jsfried** [comment]
Well, it turns out that in our users guide, we tell users to add the seedlings in to the database in order to do REPUTE analysis, by adding them to the tree list (also so that FVS will model them forward). I changed a tree into a seedling in master.tree (by changing its diameter to 0.1). If you don't change its volume, biomass etc., it will process through the system just "fine", and it ends up in the BioSum_Calc folder's cut list. But, if you null out its VOLTSGRS or DRYBIOT (realistic simulation of copying the seedlings to the tree table as demonstrated in fvs\scripts\SCRIPT_VB_AddSeedlings.txt), Processor will crash, no matter what settings you specify for smallest tree to be cut or utilized, etc. We do need to keep seedlings (trees with dbh < 1.0 OR null or zero VOLTSGRS or DRYBIOT) out of the cutlists so that Processor does not crash. Tyler, can you take another stab at this? There is value in having the seedlings in the FVSIN database so that they can be worked with in FVS both to grow forward into trees, and to do a REPUTE or REPUTE like analysis to determine appropriate regen parameters to model, and they showed  up in the FVS cut list because I made a Rx that whacked every tree every cycle (then planted new ones), just to stress test our system. What needs to happen is that the ones not meeting the conditions specified above need to NOT be passed through to the BioSum_Calc cutlist table. @sorgtyler @lbross

**Comment by lbross** [comment]
Closing
