### ISSUE TITLE
PROCESSOR: Prevent crashes related to missing harvest method

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#145]
1. If 'Defined by treatment' is selected, check to see that a harvest method is associated with each treatment in use. If not, warn the user and abort.
2. When user selects 'Specified below' or 'Lowest per acre cost', and the selections are blank, set selections to Ground-Based Mech WT for gentle slopes and Cable Manual WT for steep slopes. The latter should occur in very few cases. Only when it is a new scenario and 'Specified below' hasn't been set.

**Comment by jsfried** [comment]
Tested out fine.
