### ISSUE TITLE
CORE: Update default maximum yarding distance allowed

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#147]
Update the maximum yarding distance allowed for both Low and Steep slopes to 2500 feet. (uc_scenario_filter.cs)

**Comment by lbross** [comment]
From @jsfried: I had a good conversation today with Lisa Ball at Region 6 NFS—she is responsible for forest engineering relating to NFS forest operations for the west coast. I learned from her that maximum yarding distance depends on Rx, owner and harvest system. With clearcuts only, it is conceivable to go up to 5000 feet on steep or gentle slopes, but quite rarely done—they would build a road if on private land, to make the yarding shorter (and less costly). NFS does not build roads, so they might not even try to get to something anywhere near that far. On gentle ground, 1500 foot is the max distance for a skidder, 1000 feet for a tractor, and 2500 feet for a forwarder, though on NFS ground, 5000 feet is conceivable. The steep/gentle breakpoint on NFS lands tends to be at 30-40%.  Maximum cable distance for most systems is 2000 feet of doing anything other than a clearcut. We can share this info in the users guide and help screen so that users can make choices guided by the harvest systems they have specified, but for defaults, I think 2500 feet on both steep and gentle ground make sense.

**Comment by lbross** [comment]
Yes. These will be the defaults for a new core analysis scenario but they can be over-ridden

**Comment by jsfried** [comment]
Tested. Looks good!
