### ISSUE TITLE
PROCESSOR: SQL error when copying tree species groups between scenarios

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#153]
if the common_name contains an "'". For example: Sargent's cypress. This was experienced by @carlinstarrs, @jsfried, and @lbross in the CEC project.

**Comment by lbross** [comment]
uc_scenario_tree_groupings.saveTreeGroupings_FromProperties(). Needed to add oAdo.FixString to escape any "'" in the common_name. This will be in the next BioSum release.

**Comment by jsfried** [comment]
No problems with apostrophes now.
