### ISSUE TITLE
DATABASE: Improve error handling for oracle errors during the oracle FCS_BIOSUM process

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#158]
Currently, the plot input process will continue with the input of the data even if oracle fails.  My recommendation is to display a dialog if the Oracle process fails with a message something like

The oracle process to assign values to tree VOLUME and BIOMASS columns failed. To continue the plot input process, click <Continue>. To Cancel the plot input process, click <Cancel>

(uc_plot_input.cs)

**Comment by jsfried** [comment]
I can imagine a situation in which it might be preferable to add a third option -- continuing without generating more error pop-ups vs continuing until another error generates another popup.

**Comment by sorgtyler** [comment]
During `uc_plot_input.UpdateColumns`:
```csharp
m_oOracleServices.m_oTree.GetBiosumVolumes();

SetThermValue(m_frmTherm.progressBar1, "Value", 4);

if (m_oOracleServices.m_intError == 0) //m_intError==-5 when this issue occurred, which is why this block of code was skipped
{
    SetLabelValue(m_frmTherm.lblMsg, "Text", "Update tree VOLTSGRS column with Oracle Calculated Values...Stand By");
    frmMain.g_oDelegate.ExecuteControlMethod((System.Windows.Forms.Control)this.m_frmTherm, "Refresh");
    string strConn = m_connTempMDBFile.ConnectionString;
    p_ado.CloseConnection(m_connTempMDBFile);
    p_ado.OpenConnection(strConn, ref m_connTempMDBFile);
    p_ado.m_strSQL = "UPDATE " + m_strTreeTable + " t " +
                     "INNER JOIN fcs_biosum_volume f " +
                     "ON t.cn = f.tre_cn " +
                     "SET t.VOLTSGRS = f.VOLTSGRS_CALC," +
                         "t.DRYBIOT  = IIF(t.DRYBIOT IS NULL,f.DRYBIOT_CALC,t.DRYBIOT)," +
                         "t.DRYBIOM  = IIF(t.DRYBIOM IS NULL,f.DRYBIOM_CALC,t.DRYBIOM)";
    if (frmMain.g_bDebug && frmMain.g_intDebugLevel > 2)
        frmMain.g_oUtils.WriteText(frmMain.g_oFrmMain.frmProject.uc_project1.m_strDebugFile, p_ado.m_strSQL + "\r\n\r\n");
    p_ado.SqlNonQuery(m_connTempMDBFile, p_ado.m_strSQL);
}
//Add an else if (...) to create messagebox to inform user, give options on what to do next.
```

**Comment by jsfried** [comment]
@lbross @sorgtyler Can someone tell me how to force ORACLE FCS_BIOSUM to fail? I tried putting in non-existent species codes thinking that would do the trick, but it happily loaded the plots anyway, and just left all the volume columns blank. Just need to make it fail somehow to validate.

**Comment by lbross** [comment]
Closing. Can't find a good way to force ORACLE FCS_BIOSUM to fail.
