### ISSUE TITLE
FVS: Add an FVS location parameter into BioSum

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#159]
Some plots (non-USFS) don't have forest admin codes associated with them so FVS uses a generic location code. When left out, FVS resorts to a default code for the variant, which may or may not be very representative of the conditions that exist where the plot exists.

**Comment by lbross** [comment]
Steps to resolve this issue:
1. Add column to fiadb_fvs_variant table. This table is located in the ref_master.mdb that is associated with an individual project. Populate the column for every plot using and overlay of FVS_Variants_and_Locations map (Jeremy)
2. Update code that generates FVS files to include the location code (Tyler)
3. Update the audit that automatically assigns FVS variants to also assign the location code (Tyler)

Question: Does it make sense to leave this table at the project level? Or should we move it into the centralized BIOSUM_REF.ACCDB where it can be used by all projects?

**Comment by lbross** [comment]
We will move the fiadb_fvs_variant table from the project-specific ref_master.mdb to the centralized biosum_ref.accdb as part of this implementation

**Comment by lbross** [comment]
Additional work is needed on the uc_plot_fvs_variant.cs form to complete this request.
1. Add FVSLocCode to plot table
2. version_control needs to add FVSLocCode to plot table for legacy projects (Lesley). Analysts will need to run the 'Check for plots without location codes' audit to update the location codes for legacy projects.
3. The FVS_In process needs to get the location code from the plot table rather than the fiadb_fvs_variant table
4. Add another column to the grid on the 'Check for plots without location codes' for the location code
5. Use the fvs_variant code in this audit as an example for how to process the location code. Users should be able to update missing location codes and these should be written to the plot table so they can be used by FVS_In
6. The button and messages will need to be updated slightly to include both fvs variant and fvs location code

**Comment by lbross** [comment]
Sample audit error message found in testing. It is confusing because the top message notifies about 7 plots while the bottom messages notifies about 8:
![image](https://user-images.githubusercontent.com/11527966/46698588-613db100-cbcc-11e8-9d73-7a1a94251e8d.png)

**Comment by lbross** [comment]
This issue has been resolved except for a minor question about the audit error message displayed above. The cause of differing plot counts in this error message are plots in the plot table that have variant and location codes that are different from the fiadb_fvs_variant table. After working with @sorgtyler, we have two alternatives to improve this message.
1. Change the Additional Information message to say "x StateCd + CountyCd + Plot + Variant Combination(s) were either NOT FOUND or DID NOT MATCH entries in the fiadb_fvs_variant table. The downside of this approach is that we don't have a UI for locating/updating the entries that don't match.
2. Update the query to NOT count plots that don't match fiadb_fvs_variant when generating the count for the 'Additional Information' message. We assume here that the analyst knew what they were doing when they assigned a different fvs variant and/or location code. We need confirmation from @lpotts that Tyler's proposed updated query is good.

**Comment by jsfried** [comment]
Nice job, everyone. This issue had several facets, now all tested. Assignment of location codes now seems to work great, for new and legacy projects.
