### ISSUE TITLE
PROCESSOR: Implement OpCost 10.1 with ba_frac_cut input

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#162]
See [ProcessorRedesignObjects.docx](https://usfs.box.com/s/m1wi48qszwqjh9mwtw14noibumbgg1xl) for implementation details. Below is the original request from @jsfried:

There are two (a chainsaw and a skidder) that rely on intensity as an input, where intensity is the percent of the basal area in the stand that gets harvested. How difficult would this be to add as a column in OpCost_input (as a proportion, not a percent)? To calculate it, we would need to sum, from XX_PXXX_TREE_CUTLIST.FVS_Tree, (tpa* pi * (dbh/24)^2) for all cutlist trees for that stand-package-rxyear combo and divide that sum by  PREPOST_FVS_SUMMARY.PRE_FVS_SUMMARY.BA for that same combo.

**Comment by lbross** [comment]
After a discussions with @jsfried, I need to update the ProcessorRedesignObjects.docx. After this is reviewed/approved, I will update the code, validate the results, and supply a sample opcost input file to @jsfried  and @sloreno

**Comment by jsfried** [comment]
On page 10 of ProcessorRedesignObjects.docx, in BOTH instances, return a value of -1 and we will not use the equations in OpCost that depend on this baFracCut. i.e., 
totalBaFracCutNumerator / baFracCutDenominator
if baFracCutDenominator is null or 0 then write entry to log and return -1 in this field
if baFracCut not between 0 and 1, then write entry to log **and return -1 in this field**

**Comment by lbross** [comment]
This is done in my private repository and ready for deployment

**Comment by lbross** [comment]
Closing. This is superseded by issue #172 for OpCost changes
