### ISSUE TITLE
PROCESSOR: Remove 'Lowest Per Acre Cost' option from Harvest Method selection screen

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#163]
@jsfried  wants to hide the 'Lowest Per Acre Cost' option until we have confidence in OpCost output and there are multiple equations per harvest system. We will:

1. Hide the 'Lowest Per Acre Cost' option on the Processor Harvest Method selection screen
2. Reset the harvest method selection option to 'Defined by treatment' for legacy projects that may have been using 'Lowest Per Acre Cost'
3. Stop creating OpCost_Ideal_Output in the OpCost .R script
4. Verify that BioSum doesn't read OpCost_Ideal_Output if 'Lowest Per Acre Cost' isn't selected in item 1

**Comment by lbross** [comment]
This is done and waiting to be deployed from my private repository

**Comment by jsfried** [comment]
Looks fine.
