### ISSUE TITLE
DATABASE: FIA datamart no longer contains ACCESS databases

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#164]
BioSum requires FIA data to be in an MS Access database for plot loading. This summer the FIA datamart ceased to provide data in MS Access database format. Our users can download the data in .CSV format but it needs to be loaded into an .mdb in specific format. 

From @lpotts: Downloading the CSV file and then exporting to ACCESS will not work when trying to import data into a BIOSUM project.  The reason is that ACCESS will try to assign data types based on the CSV data and will generally assign text data types with a length of 255 which will not work for importing the data into BIOSUM.  BIOSUM has data type expectations in the input process. BIOSUM was designed to import ACCESS tables that were downloaded from the data mart.

**Comment by lbross** [comment]
@jsfried found a workaround by loading the .CSV file into an old Access file with an empty table. If we confirm this works, this process needs to be documented and shared. We also need to develop a long-term solution perhaps using mySql or PostGIS format as input

**Comment by jsfried** [comment]
Not exactly. The FIADB style Access database from 2017, with ALL TABLES DELETED, was used to access and run a form called "Load a State’s FIADB tables". Running that form and pointing it to the directory to which one has unzipped all the CSV files for a state (specifically, to the file PLOTSNAP.CSV in that Directory), it should import all the CSV data correctly into Access tables. This is a kludge that works for now but may not in the future, so we should adapt to POSTGRES or mySql (if FIADB ends up getting distributed that way).

**Comment by jsfried** [comment]
Here is the template for loading csv files.
[https://usfs.box.com/s/iyytlji05blrg2e77rxnarxkhvogbdn5](url)

**Comment by lbross** [comment]
The interim MS Access solution makes a lot more sense having seen the MS Access template and its accompanying VBA code. I am moderately fluent in VB so if there are some tweaks required to continue using this template, I think we could handle it. Another option would be to translate the code to C# and add it to the BioSum application as an alternative way to load plots. Not necessarily advocating for this approach, but it is an option if our backs are against the wall and we don't have the resources to switch to another database type.

**Comment by lbross** [comment]
The MS Access template is maintained by the Northern Research Station FIA Unit. @jsfried and @lpotts will request that FIA continue to support this template and method of loading FIA data into an Access database. As long as the template works, we don't plan to make any changes to the BioSum plot loading process.

**Comment by lbross** [comment]
Closing this but refer to issue #206. The ultimate solution is to be able to import plots from SQLLite. This is the go-forward database from FIADB
