### ISSUE TITLE
Test issue for notifications

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#17]
Please reply to this issue to indicate that you received the e-mail notification when it was opened. This is in response to our discussion on GitHub notifications last week. Please reply rather than reply-all to minimize e-mails. This test will also show how replies to GitHub e-mail are automatically added to the issue thread. Thanks!

**Comment by jsfried** [comment]
received

**Comment by lbross** [comment]
Sending update to see if Sara receives e-mail. Sara, please reply if you receive. Not reply-all

**Comment by lbross** [comment]
Closing issue. All are now receiving emails.
