### ISSUE TITLE
TOOLS: Scan and synchronize repair tool doesn't recognize appData folder

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#170]
Update this tool so that it uses the macro variables functionality to locate the tables in the appData folder. This was missed during the initial implementation of the appdata folder.

**Comment by lbross** [comment]
I excluded the data sources that reside in the appdata folder from the grid that appears on this screen. It doesn't make sense for them to be listed because the project root folder is not a component of their path. I also found a bug that prevented the strProjectPath from being extracted from datasources in the db folder. And I fixed a glitch where Biosum crashed when you closed it with this tool being open. This will be in the next Biosum release.

**Comment by jsfried** [comment]
Mission accomplished.
