### ISSUE TITLE
OpCost equation QA

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#172]
Jeremy ran OpCost with some CEC data to generate machine time graphics. He then focused on machines where disparities were large and/or estimates seemed unreasonable. His recommendations are attached. Sara will need to investigate issues around HELI_04; the rest can be dealt with by editing machine equations in opcost_equation_ref or editng equations out of (removing them from) opcost_harvestequation_ref.
[QA_of_eqns_via_b&w_plots.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/2421695/QA_of_eqns_via_b.w_plots.docx)

**Comment by lbross** [comment]
Changes required on BioSum side:
1. Update harvest_methods table: Set min_yard_distance_ft to 150, min_tpa to 1, and min_avg_tree_vol_cf to 1 for all systems.
2. Add validation to uc_processor_scenario_harvest_method.cs so that the minimum diameter for large log trees cannot be less than 10

**Comment by lbross** [comment]
We will call this version of OpCost 10.1.1

**Comment by lbross** [comment]
The release number for this version of OpCost is 10.1.3

**Comment by lbross** [comment]
Closing per @sloreno !
