### ISSUE TITLE
MS OFFICE 2016 Upgrade (Office 365)

### ISSUE THREAD

**Issue by lpotts** [USFS-PNW/Fia-Biosum-Manager#177]
Forest Service will be moving FS computers to MS OFFICE 2016 soon - it is currently in BETA mode. These questions need to be answered:  1. Will BIOSUM ADO.NET application connection strings need to change?; 2. Will the native ACCESS DAO Interop for OFFICE 2016 still work in BIOSUM? (ie creating table links, creating accdb files, etc);

**Comment by lbross** [comment]
Closing. BioSum appears to work with MS Access 2016 and 365 as long as the MS Office 2013 32-bit runtime library is also installed. The documentation has been updated.
