### ISSUE TITLE
FVS: Add capability for custom database and table for manually calculated variables

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#182]
@jsfried is wondering whether we (analyst types like me and Sara) can make a new table FVS (pseudo)output type called PREPOST_FVS_CUSTOM to hold analyst generated PRE and POST info derived from multiple FVS output databases and tables? Would be a little cleaner than just adding to SUMMARY or COMPUTE because what if you need to reimport some FVSOUTPUT data later? You would lose your calculated values just for the rows that were imported and it would leave your standard FVS OUTPUT table in a mixed state. If I make this PREPOST_FVS_CUSTOM database containing tables named FVS_CUSTOM_PRE and FVS_CUSTOM_POST, will these tables and their attributes be automatically available to the analyst in Treatment Optimizer? Or does BioSum only look for databases and tables in a standard list of expected FVS outputs? If the latter, can we add CUSTOM as a database and table type to allow analysts a cleaner solution than just appending endlessly to SUMMARY etc.?

**Comment by lbross** [comment]
Added g_strFVSOutTablesArray to Tables.cs. The analyst will need to create a new database in the /fvs/db directory with a file name that is derived from the desired table name. In your example, the database name should be PREPOST_FVS_CUSTOM.ACCDB. The table names will be PRE_FVS_CUSTOM and POST_FVS_CUSTOM respectively. 
Required fields on this table are biosum_cond_id, rxpackage, rx, rxcycle and fvs_variant. If you want to this custom variable as the basis for weighted variables, you'll want to include data from all 4 cycles.

**Comment by jsfried** [comment]
Works beautifully! Just need to add it to documentation.

**Comment by jsfried** [comment]
All done.
