### ISSUE TITLE
MS Access: System resource exceeded errors

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#186]
A user encountered this error running MS Access 2013 on Windows ?. The error was encountered using the condition zapper and the FVS OUT audit. The image is from the condition zapper. The error message from the FVS OUT audit was:
Module - ado_data_access:SqlNonQuery 
Err Msg - System resource exceeded. The SQL command SELECT DISTINCT a.standid,a.year,b.rowcount INTO temp_rowcount FROM FVS_TreeList a,(SELECT COUNT(*) as rowcount,standid,year FROM FVS_TreeList GROUP BY standid,year) b WHERE a.standid=b.standid AND a.year=b.year Failed

@sorgtyler was able to run the FVS OUT audit on the same CEC project successfully on his computer running MS Access 2016 (Office 365) on Windows 10. There are some online references that suggest installing a MS Access patch to resolve this issue but we would like to test on more computers before settling on this as a solution. It appears to be a computer-specific issue.

![img_0433](https://user-images.githubusercontent.com/11527966/51344667-ff53d980-1a4d-11e9-8b4d-170dd2240496.jpg)

**Comment by lbross** [comment]
Closing. This has not been a problem for other users and we have been unable to recreate. Plus the hotfix is no longer available for MS Access 2013

**Comment by sorgtyler** [comment]
Oh, the error message has to do with creating index names for faster deletes. The code tries to create and index called columnName_delete_idx and deletes it after successfully removing records from the current table.

If you cut the delete conditions process short, or an error occurs, subsequent runs will try to create an already existing index.

I tried to check for indices with SQL, but I couldn't figure that out. Deleting an index that doesn't exist causes an error too. How should I do error handling for this piece of the code?

**Comment by lbross** [comment]
Was this comment intended for issue #191? I think you could create a new dao_data_access method similar to the existing TableExists method that uses the TableDefs property to see if an index exists. Indexes is a method for TableDefs that returns all of the index names. I looked into doing this for version_control but was able to get away without adding it.

**Comment by sorgtyler** [comment]
@lbross I see. I'll look into doing this when I start working on the prescription zapper over the next week or two.
