### ISSUE TITLE
DATABASE: Make project name editable

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#189]
Can we make the project name editable in the project properties dialog? Analysts can (and frequently do) change it manually as the project_id field in the project.mdb database, so why not make it accessible via the properties form? It is not helpful to have an old project name continue to display in the BioSum window’s title bar, even after you have radically changed it and renamed the root folder.

**Comment by jsfried** [comment]
This works! Thanks Lesley.
