### ISSUE TITLE
PROCESSOR: Plots with no trees cut in cycle 1 are dropped from the analysis

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#19]
Plots with no trees cut (where no material is delivered to the landing) are not included on the TREE VOL VAL table. This removes the plots from further analysis and makes it difficult to reconcile plots in a complete analysis. If these plots are missing from TREE VOL VAL where would we like to see them in subsequent output? Additional clarification welcome/needed.

**Comment by lbross** [comment]
We will add a placeholder record to TREE VOL VAL for cycle 1 for stand/package combinations that are lacking entries for cycle 1 but do have entries in cycles 2, 3, or 4. A stand/package will be identified as a unique combination of biosum_cond_id and rxpackage in the TREE VOL VAL table. The full name of the TREE VOL VAL table is 'tree_vol_val_by_species_diam_groups'.

Will add a field to TREE VOL VAL called PLACE_HOLDER; Will populate with ‘Y’ for these added records so they can be identified. And an 'N' for all other records.

**Comment by lbross** [comment]
QUESTION: What should species_group and diam_group be set for for these placeholder records?

**Comment by jsfried** [comment]
Ideally, they would be set to some end of the scale that we aren’t using—0? 999? But not knowing how these attributes are accessed at various places in the program, I don’t know for sure that such choices would be “safe” or if they would lead to other glitches (e.g., if 999 and there is a requirement that group numbers be sequential).

**Comment by sloreno** [comment]
Seems like using a number such as 0 or 999 would be the cleanest way, in
that there would be no confusing that the record was a dummy record.
However, there would need to be, I imagine, a default diam and species
group created so that BioSum would recognize these groups without the user
having entered them. I imagine this would be a default record in the
species group table, as well as a default record in the diameter class
table.  Does that make sense?

**Comment by lbross** [comment]
It does make sense. Would appreciate @lpotts input as to whether corresponding records in the \db\master.mdb\tree_species_groups and \db\master.mdb\tree_diam_groups are required for core analysis processing.

**Comment by lbross** [comment]
Per @sloreno this is working as designed! Closing.
