### ISSUE TITLE
DATABASE: Record application version when project originally created

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#194]
We will record the application version under which project originally created in the settings.cfg file. It looks like there are subsections in this file, none of which is appropriate for this piece of data. Need to confer with @lpotts about adding a subsection.

**Comment by lbross** [comment]
Upon further reflection, we cannot store this information in the settings.cfg file. There is one settings.cfg file per computer and the analyst will likely have multiple projects that were started under different version numbers. This data needs to be stored separately in each project folder.

Some possible solutions:
1. Add a line to the current application.version file in key=value format. For example: created_version=5.8.6.
2. Add a new table to the db\project.mdb with date_created and created_version columns
3. Add a new text file at the project root similar to the existing project.version file named created.version with just the version number in it

Since BioSum won't be consuming this information and it is just for analyst reference, would like to hear from @jsfried  which of these is preferred. They would all require a similar effort. Also if @lpotts  has any other suggestions.

**Comment by jsfried** [comment]
# 2 is most elegant and keeps it more internal (less likely to be manually adjusted or lost as a project gets moved around). That would be my preferred solution. I don't want to see a proliferation of txt files in the project root, for sure.

**Comment by jsfried** [comment]
I guess the number sign does weird formatting tricks!

**Comment by lbross** [comment]
Yes! Apparently the number sign = bold. Will move forward with the new table as time allows. Thanks!

**Comment by lbross** [comment]
Choice 2 is so elegant that it has already been done! The date and originating project version exist in the db\project.mdb\project table. The field names are created_date and application_version. The cec_20190115 was created using v5.8.4.
