### ISSUE TITLE
FVS: RxPackage item screen; Clear button doesn't do anything

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#195]
In the Treatment Package Item dialog, the Clear button in the lower right quadrant does not seem to do anything.

**Comment by lbross** [comment]
Remove this button from uc_rx_package_edit.cs. It serves no useful purpose. If you don't want a treatment for the selected simulation year, use the Skip Treatment checkbox that clears everything out. If you do want a treatment, you need to select one from the RxID list. When you select an RX, the Description is populated.

**Comment by jsfried** [comment]
The button is gone, as advertised. The functionality is almost but not quite perfect. Selecting a Rx for a cycle does populate the description field in the upper half of the dialog, but not the one in the mini-table in the lower left corner; however, if you save and come back to the dialog, that one will then be populated. Not a deal-breaker, but it is a small idiosyncracy that would be nice to lose if it is easy to do so. @lbross

**Comment by lbross** [comment]
I added code to set the rx description when RxId is changed in the lower right-hand corner. This populates the description in the mini-table in the lower left hand corner when you use the OK button to choose your Rx. The Skip Treatment button clears everything out when you use the OK button the select that. This is ready for deployment in the next release; Either 5.8.7 or 5.8.8

**Comment by jsfried** [comment]
Seems to work well, thanks!
