### ISSUE TITLE
DATABASE: Implement package zapper

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#205]
@jsfried has requested a prescription zapper similar to the condition zapper. All tables after the FVS out process have a condition id and rxPackage. The input should be a list of RxPackages. There may be opportunities for code re-use with issue #191.

**Comment by lbross** [comment]
I just looked through the Processor tables to see if any tables were there that had packages to be zapped. I did not find any. The list of variant/packages to process comes from the rxPackage table so if the package is deleted from there, it won't show up on the Processor list.
There is a list of scenario + condition + rx on the additional harvest costs table that MAY be able to be deleted but we're not currently recording the rxPackage on this table so there is no way to safely do it. If it is important to delete rxPackages from this table we would need to start recording the rxPackage number when its created.

We should delete packages from tables in optimizer/db/prepost_fvs_weighted.accdb. I think we are already deleting conditions from this table in the condition zapper.

Everything else in these modules is created each time a scenario is calculated so if the rxPackages aren't in the earlier modules, they won't show up in these.

**Comment by lbross** [comment]
@sorgtyler When talking to Jeremy today on an unrelated matter, we were reminded that the package zapper also needs to delete records from the tables in optimizer/db/prepost_fvs_weighted.accdb associated with the packages to be removed. These tables need to stay in sync with their FVS PRE/POST table sources.

**Comment by lbross** [comment]
@sorgtyler I may be able to add this directory to the package zapper. I think I did something similar with the condition zapper. I will take a look

**Comment by lbross** [comment]
@sorgtyler: We uncovered a couple more things that should be fixed on the package zapper. 
1) When using the record count option, the final MessageBox says "successfully deleted data associated with X prescriptions". This is misleading because the data wasn't actually deleted, just counted. Can we change the MessageBox to "See C:\Docs\Biosum\Blue11_demo_588_package\db\biosum_deleted_packages_202001160141_no_deletes.txt for a summary of the records that would be deleted" ?
2) This is also a problem with the Condition Zapper
3) Don't allow compact to be checked if you are only record counting as you will get a LOT of warning messages to click through. It (compact) really should only be allowed if count only is not checked.

**Comment by jsfried** [comment]
These issues are fixed. I recommend not worrying about orphaned records in the additional harvest costs table.
