### ISSUE TITLE
DATABASE: Import plots from SQL Lite

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#206]
State-level FIA data is now available on sqlite format. Can we write an importer that writes these tables to the Access format used by BioSum? An interim alternative is to test and document a manual process.

**Comment by lbross** [comment]
See e-mail from @jsfried "Glitch with tree table in SQLite OR database on FIA DataMart". In a nutshell Jeremy tried to use ODBC to make the required SQLite tables accessible to Access. The recommended route of adding links to the tables did not work. BioSum could not see them. Jeremy tried manually importing each table into a new database. Everything seemed to work except for the tree table. He got an ODBC error

**Comment by jsfried** [comment]
We have successfully imported from SQLite data for a few projects now. Delightful to now have this capability! Still to be worked through are some issues around cull, defect, correct TPA on partial plots but the main capability of loading from SQLite is implemented successfully-- yay!
