### ISSUE TITLE
OPTIMIZER: Updates to tables in optimizer_results.accdb

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#210]
The following errors have been uncovered with the output tables from Treatment Optimizer. This list will be updated as additional issues are found that may be fixed within the scope of this deployment:
1. These tables contain economic metrics for cycle 1 only although their names start with "all_cycles" if a weighted variable is used: XXX_stands, XXX_stands_air_dest, XXX_own_sum, XXX_own_sum_air_dest, XXX_psites_sum
2. Stands using ACD are usually absent from the air_dest tables. Use usebiomass_yn = 'N' from the product_yields_net_rev_costs_summary_by_rx instead
3. Stands that were not assigned a processing site appear in the XXX_effective and all subsequent tables. They should not. This is also true for  product_yields_net_rev_costs_summary_by_rx and product_yields_net_rev_costs_summary_by_rxpackage.
4. Fields related to haul costs and plot accessibility that are used by Treatment Optimizer live in the Plot and Cond tables. These values are overwritten each time Optimizer runs. You cannot compare historic values between scenarios.
5. Multiple column labels and calculations in the XXX_stands table are incorrect. A document with changes for this table was provided by @jsfried

**Comment by jsfried** [comment]
This is a huge improvement. Work remains to fully document these tables in the user guide, but the coding seems done well.

**Comment by lbross** [comment]
Good news! Does this mean you are done with validating v5.8.8 and ready for me to put out a new build for issue #208 and issue #226 ? Also, let me know if I can assist with documentation.

**Comment by jsfried** [comment]
Not quite. There a few more to do and I was running into some weird stuff last night in a new project I built to test the issues that require a new project so I am thinking I won’t be done til sometime this weekend. Will keep you posted. Have to go see my mom now.

Sent via iPhone. Forgive the brevity, typos and lack of nuance.
________________________________
