### ISSUE TITLE
FVS: Populate gis_yarding_distance from biosum_ref database

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#212]
1. Add move_distance_ft field to fiadb_fvs_variant table in biosum_ref.accdb
2. Update plot loading process to set the  plot.gis_yarding_distance to the MoveDistance_ft value (if present)

**Comment by sorgtyler** [comment]
Should I just extend uc_plot_input to check if biosum_ref.fiadb_fvs_variant has the new column, and assign the value for that plot if it's not null?

**Comment by lbross** [comment]
That makes sense to me. We can double check on the call this afternoon.

**Comment by lbross** [comment]
@jsfried is populating the fiadb_fvs_variant table.MoveDistance_ft. He requested that we rename plot.gis_yard_dist to plot.gis_yard_dist_ft. @sorgtyler agreed to make this change throughout the solution. @lbross will write version_control code when ready.
@lbross will also update Processor to screen plots where gis_yard_dist_ft < 0 and not send them to OpCost. She will write an entry to the log indicating how many stands were dropped for this reason.

**Comment by lbross** [comment]
FYI found that Processor is treating null yarding distances as zeroes. I am going to switch this to -1 so that our updated error handling will exclude these plots. This will not update any existing tables, just the creation of opcost_input.

**Comment by lbross** [comment]
Closing per @sloreno !
