### ISSUE TITLE
OPTIMIZER: Add field indicating which cycles had non-zero harvest to TREE_VOL_VAL_SUM_BY_RXPACKAGE

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#218]
From @jsfried: It would be useful in analysis to have a coded variable TEXT(4) indicating which cycles had non-zero harvest as determined from the tree_vol_val_by_species_diam_groups table, for example: ‘3030’ would indicate both merch and chip volume harvested in cycles 1 and 3; ‘1002’ would indicate merch vol harvested at cycle 1 (but not chips) and chip volume at cycle 4 (but not merch). This field would be REALLY useful in several analyses I can think of.

**Comment by lbross** [comment]
Name for this new field?

**Comment by jsfried** [comment]
HvstTypeByCycle

**Comment by lbross** [comment]
Will name field HVST_TYPE_BY_CYCLE. Sample of sql to populate cycle 1 position of field:
SELECT BIOSUM_COND_ID, RXPACKAGE,
IIF (chip_vol_cf > 0 AND merch_vol_cf > 0, '3', 
IIF (chip_vol_cf = 0 AND merch_vol_cf = 0, '0',
IIF (chip_vol_cf > 0, '2','1'))) as cycle_1
FROM tree_vol_val_sum_by_rx_cycle
WHERE rxcycle = '1';

**Comment by jsfried** [comment]
Seems to work great! THanks.
