### ISSUE TITLE
OPTIMIZER: Automate process to load tables in gis_travel_times.accdb

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#219]
Tim created master travel_time and processing_sites tables with records from eight western states. A BioSum project only needs the records related to included plots. We hope to automate the process of loading the project-specific tables from the master tables.

The .accdb containing the master tables will be distributed in the db directory of the application install directory. The loading process will copy the applicable records in the project gis_travel_times.accdb.

The master and project-specific travel_time tables have the same schema. Tim is working on documentation for the processing_sites tables so that we can reconcile the master with the project-specific tables.

**Comment by lbross** [comment]
When loading the project tables from the master database, BioSum will look in the user's AppData folder for the master database. BioSum will warn if the master database is missing and not begin the load process. 
The master database will get into user's AppData/FIABiosum directory one of the following ways:
1. When BioSum starts up, it will look for the master database in the AppData folder. If the database is missing, it will look in the setup > FIABiosum folder for the master database. If it exists, Biosum will copy the master database to the AppData/FIABiosum folder. If it doesn't exist, the process will exit silently. The latter is the most likely scenario since this is a a new implementation.
2. The analyst receives the master database from the BioSum administrator and saves it to the AppData/FIABiosum folder

**Comment by jsfried** [comment]
When referring to this database, especially in materials for distribution such as installation instructions, maybe we want to make the name more different from our existing master.mdb database in \db? i.e., refer to it as gis_travel_times_master.accdb?

**Comment by lbross** [comment]
Closing per @sloreno !
