### ISSUE TITLE
OPTIMIZER: Allow analyst to select packages to be included in analysis

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#226]
Add a new tab to the Optimizer scenario interface that allows the user to exclude variant/package combinations from the analysis. Similar to Processor selection.

**Comment by lbross** [comment]
The packages available to Optimizer can be pulled from the harvest_costs table associated with the selected Processor scenario. Thus, we can only generate this list after a Processor scenario is selected. FVS_variant is not in the harvest_costs table. FVS_variant is in the plot table.

If all prescriptions in a variant are not selected, we can exclude that variant from Optimizer when applying the user-defined plot filter.  We can exclude by package when generating the validCombos table.

**Comment by jsfried** [comment]
Works great! And nicely implemented. Leaving a package unchecked keeps it out of the results, except for context tables like harvest_costs_C. I don't see any table in the output database that tracks which packages were included, or not, in the optimization-- I suspect this is somewhere in optimizer\db but it would be nice to have as a context table also, for completeness off the optimization_results db.

**Comment by lbross** [comment]
With the current implementation excluding a package by unchecking it does not exclude it from the context tables. Also, there is no output database that tracks which packages were included. This works like the check boxes in Processor where they are only applied to the current scenario run.

I could add a table to the output database that records the variant/packages that are included. One could also run a query on the validcombos_fvsprepost for the included variant packages. Although I just noticed the fvs_variant is missing from this table in the sqlite export, so I need to fix that.

We could exclude the unchecked variant packages from the larger tables in the context database like tree vol val and harvest costs. We don't store the fvs_variant in these tables so I'd have to do some sort of join with the valid_combos table. I'm not sure if that would be better or worse performance than including everything.
