### ISSUE TITLE
Add menu item and .XPS document for Release Notes

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#230]
Add a menu item to the Help menu directly above 'About FIA Biosum' called 'Release Notes'. Clicking on this item will pop-up an XPS document viewer that contains the release notes. We will use the same architecture that we use for the Help screens. The Release Notes will be converted to .XPS and distributed with the application as the Help documents are.

**Comment by lbross** [comment]
This is done and ready for deployment. In the future, the release notes will be maintained in the Help subdirectory of Fia_Biosum_Setup similar to the other help.

**Comment by jsfried** [comment]
Looks good!
