### ISSUE TITLE
OPTIMIZER: Add exporter to write output to SQLITE database

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#231]
Add a button to the Optimizer button group to export output tables (optimizer_results.accdb, context.accdb, and fvs_context.acdb to SQLITE databases. Do we want to give the option of selecting tables? Or just migrate all tables? Are there any tables we want to exclude?

Will work on the databases in order that they are listed.

**Comment by jsfried** [comment]
In addition to these tables, the tabling program will require the 4 POP tables that I think get imported to master. For now, let's do optimizer_results while we are testing things. We'll probably need the others eventually though, also.

**Comment by lbross** [comment]
Sounds good. Just add them to this issue when you think of them. That way they won't get lost.

**Comment by lbross** [comment]
Add Growth_Acct and LAND_ONLY fields to pop_eval table. These fields should have a datatype of TEXT and be null. Note that native SQLite does not have CHAR field data type of delineate the size of the field.

**Comment by lbross** [comment]
The POP tables only hold the data that is needed for the PLOT INPUT process. They are initialized for each PLOT INPUT session. If we want to support exporting all POP tables that have ever been used for importing PLOTS in a project, we will need to develop a new process. Currently the program exports the contents of the POP tables in master.mdb as of the time of export.

**Comment by jsfried** [comment]
Tried to   export a database (without context tables) from blue demo wtd_pmod and got error:
in the sqlitelog.txt:

START: SQLITE export Log 8/16/2020 8:06:33 PM

Project: Demo_DATABASE
Project Directory: W:\bs_projects\Blue11_88_demo
Scenario Directory: weighted_ptmod
---------------------------------------------------------------
CreateResultsSqliteDb ERROR!! 
Missing the DataColumn 'STATUS' for the SourceColumn 'STATUS'.
   at System.Data.Common.DbDataAdapter.UpdatingRowStatusErrors(RowUpdatingEventArgs rowUpdatedEvent, DataRow dataRow)
   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
   at FIA_Biosum_Manager.uc_optimizer_sqlite_export.CreateResultsSqliteDb()

I am not sure in which table “STATUS” is missing, but the DB file that it created has 15 tables and no POP tables.

Also, BioSum would not allow me to exit the optimization task bar progress  screen (which I had left open when I pushed the button to make an SQLite output) after this SQLite db write failure-- had to kill the BioSum task'
--

**Comment by lbross** [comment]
Per a separate e-mail, I suspect the status column is missing from the processing_site table. This field was added during the work we did with Tim and projects with an older gis database may have this issue. It won't be a problem going forward. I tried to replicate your issue with the task bar and couldn't. Did you have any other tasks running at the same time you were trying to make an SQLite database?

**Comment by jsfried** [comment]
I added the status column. The database now exports fine. Just for grins, I tried exporting JUST the context database. It does that too, though it also brings along the POP tables. Not sure why you would want just the context database as a .DB but BioSum can do it. Also, I updated the documentation for this button, so now you can steal some of it to make a help button.
