### ISSUE TITLE
Problem with record counts in FVS output import module

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#232]
Using Blue Demo 11, I sought to attempt an FVS output import of package 9 (to test whether oracle was correctly populating volume and biomass). Apparently I had not turned off record counting and I ended up getting errors displayed 
![2020-02-09_21-13-19](https://user-images.githubusercontent.com/17485472/74122735-0ed62100-4b81-11ea-96c9-180696894814.png)

Larry thinks that it might be due to a bug in the application because the record count exceeds the data type used to hold the record count. If I turn off record counting, I don't have any error messages displayed. I got error messages displayed for multiple packages when record counting was allowed.

**Comment by lbross** [comment]
Please see issue #186. We ran into this a while back, also on Jeremy's computer. Not sure if it is the same computer. Tyler and I looked into it at that time and neither of us could recreate the error. If it is a column size error, we should get the same error on all computers.

@jsfried: Did you encounter this error using the same BlueDemo that we've been using for a while? If so, I will try to load FVS out on my computers, with record counting turned on, to see if I get the error. If not, please post the project at your convenience.

**Comment by lpotts** [comment]
Fixed this issue. The fix will be included in the version that implements the FS NETWORK for volume/biomass compilation. @lbross @jsfried

**Comment by lbross** [comment]
From @jsfried: the FVS output loading process and now completes without error, even with record counts not suppressed
