### ISSUE TITLE
OPTIMIZER: SQL error when loading scenario with no psites in travel_times table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#233]
BioSum crashes when loading an Optimizer scenario if there are no psites in the travel_times table. Workaround is to put at least one site in the table. Also fix error when trying to delete old links from \fvs\db\biosum_fvsout_prepost_rx.mdb when the database doesn't yet exist. This error can be ignored as BioSum will create the database when it creates the table links, if the database isn't there.

**Comment by jsfried** [comment]
no longer crashes.
