### ISSUE TITLE
OPTIMIZER: Update results.accdb file name and record version number

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#234]
Update the long results.accdb file name to remove the seconds. We don't need this degree of precision. optimizer_results_all_cycles_net_revenue_1_2019-03-06_14-35-01.accdb becomes optimizer_results_all_cycles_net_revenue_1_2019-03-06_14-35.accdb.

Add a table to optimizer_results.accdb called version. This table will have one row and one field called 'application_version'. The row will contain the version of Biosum that was running when the Optimizer scenario was run.

**Comment by jsfried** [comment]
Works great! Thanks!
