### ISSUE TITLE
OPTIMIZER: Glitches with copy function

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#235]
Both of these glitches occur when a scenario is copied and then immediately run. A workaround is to copy the scenario, close it, reopen it, and then run.
1. Duplicate primary key error when populating diameter_spp_grp_ref_C table in context.accdb. Unchecking the option to create the context database is another workaround to avoid this.
2. Empty tiebreaker tables in optimizer_results.accdb when using a net revenue filter. All rows in the optimization table are null in the net_revenue_1 field. This causes the affordable_YN flag to be set to 'N' for all rows which in turn prevents any rows from being added to the tiebreaker tables. The problem lies in correctly calculating the net_revenue_1 field after a copy.

**Comment by lbross** [comment]
Optimization variables parameters do not display when the scenario properties are loaded for the text file and screen display. This was due to an optimization scenario property (rxcycle) that was missing from the loadvalues function.

**Comment by jsfried** [comment]
These issues are fixed. Thanks!
