### ISSUE TITLE
PROCESSOR: Create text file to log settings for each run

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#238]
Start printing a text file containing the settings for each Processor run so the analyst has an audit trail. The text file will be saved in the processor/scenario1/db directory where scenario1 is the name of the scenario. The name of the text file will be params_scenario1_2020-01-09_0350 which is the year-month-day-hhmm that the scenario was run. This can be reconciled with the DateTimeCreated field in the Processor tree vol val and harvest_costs tables.

**Comment by jsfried** [comment]
Actually, the file shows up in the scenario1 folder, not it's db subfolder, but that seems OK to me. The contents look good.
