### ISSUE TITLE
FVS: Cosmetic updates to uc_fvs_input

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#239]
1. Remove 'Plots Missing FVS Variant Value' and 'Tree Species Missing FVS Variant Value' buttons and labels from form. Remove accompanying queries that populate these labels when the form loads.
2. Rearrange 'Treatment' and 'Packages' buttons onto a single line
3. Re-label 'Main Menu' tab to 'FVS Input' and 'Options' to 'FVSIn Options'

**Comment by jsfried** [comment]
Looks great! I assume that the tab for setting the FIADB FVS input database is at this point just a file chooser function that doesn't actually load data. Is that right?

**Comment by lbross** [comment]
In the posted release, yes. The code behind it is complete and could be deployed at any time.
