### ISSUE TITLE
FVS: Max length for FVSLOCCODE is too short on grid

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#240]
The max length property for this field is set to 2 and it should be 3. As a workaround, one can use the 'Edit' button to go into the record and select the desired loc code from the list. This was a missed requirement when fvsloccode was added to this grid. The code for the fvs variant field was re-used for this field.

**Comment by jsfried** [comment]
Thanks. The Edit button does work. I assume you'll edit the length on this one and that it will correct in a future release.

**Comment by lbross** [comment]
Yes. Fixed it this morning and it will be included in the next .msi

**Comment by jsfried** [comment]
Works great now!
