### ISSUE TITLE
FVS: Start populating FVS_TreeInit.Age from FIADB data

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#243]
Add a tree age parameter to the FVS_Input options page.  FVS_TreeInit.Age will be set to FIADB.Tree.BHAge + user_parameter_from_options_menu. There are ages for about 30-40% of the trees and they are useful. We have a new project where we are using age in a prescription formulation for the first time.

**Comment by jsfried** [comment]
Perfect!
