### ISSUE TITLE
OPTIMIZER: Fails when > 1 rxPackage has the same rx for cycle 1

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#247]
The error message is:
![image001](https://user-images.githubusercontent.com/11527966/90191094-19ae8000-dd75-11ea-9f82-0ddfeac71dcd.png)

**Comment by lbross** [comment]
Found a problem with last_tiebreak_rank assignment if > 1 rxPackage shared the same rx for cycle 1. Also needed to update the compound key for all_cycles_best_rx_summary_before_tiebreaks to include rxPackage so that MS Access didn't see these rows as duplicates.

**Comment by jsfried** [comment]
Validated on 8/14/2020 with 64 bit version of 5.8.8
