### ISSUE TITLE
OPTIMIZER: optimizer_results.accdb requires repair the first time it is opened after copying/running a scenario

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#255]

**Comment by lbross** [comment]
I have tried everything I can think of to fix this with no success. This database is created initially by copying a temporary database to the designated path. The temporary database was previously an .mdb. I switched this to .accdb but no change. Since this only happens the first time the accdb is opened, I tried creating the accdb earlier on in the process. No change. We were NOT compacting the .accdb after the copy. I added a compact/sleep statement following the copy. No change. I made the sleep interval longer after the compact. No change. I tried connecting to the database after the copy/compact/sleep. No change.

Unless someone has another idea, this is likely something we will have to live with until the migration to sqlite. I also tried creating my own optimizer scenario and running it but it behaved the same as a copy scenario so it doesn't have anything to do with the copy process.

**Comment by jsfried** [comment]
I am fine with living with it until SQLite replaces Access. We must do all that we can to make that sooner rather than later and try not to get distracted with trying to avoid every possible glitch now on the Access and ORACLE base. I will try to do better about raising distractions.

**Comment by lbross** [comment]
Closing. We will not spend any more resources on this and eagerly await the migration to SQLite.
