### ISSUE TITLE
DATABASE: Update calculations for vol_ac_grs_stem_ttl_ft3

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#258]
hwd_vol_ac_grs_stem_ttl_ft3, and swd_vol_ac_grs_stem_ttl_ft3 in the COND table. These fields should use TPA * VOLTSGRS instead of the current hard-coded ratios. Also review calculation for vol_ac_grs_ft3 (and its hw/sw variations) to make sure it is using vol_cf_grs directly.

**Comment by lbross** [comment]
New SQL for vol_ac_grs_stem_ttl_ft3:

INSERT INTO cond_column_updates_work_table(biosum_cond_id, vol_ac_grs_stem_ttl_ft3) 
SELECT DISTINCT(a.biosum_cond_id),a.ttl as vol_ac_grs_stem_ttl_ft3 FROM tree t, 
(SELECT biosum_cond_id, SUM(voltsgrs * tpacurr) as ttl FROM tree 
WHERE voltsgrs IS NOT NULL AND tpacurr IS NOT NULL AND statuscd = 1 AND dia >= 1 
GROUP BY biosum_cond_id ) a WHERE t.biosum_status_cd = 9 AND a.biosum_cond_id = t.biosum_cond_id

INSERT INTO cond_column_updates_work_table(biosum_cond_id, hwd_vol_ac_grs_stem_ttl_ft3) 
SELECT DISTINCT(a.biosum_cond_id),a.ttl as  hwd_vol_ac_grs_stem_ttl_ft3 FROM tree t, 
(SELECT biosum_cond_id, SUM(voltsgrs * tpacurr) as ttl FROM tree 
WHERE spcd > 299 AND voltsgrs IS NOT NULL AND tpacurr IS NOT NULL AND statuscd = 1 AND dia >= 1 
GROUP BY biosum_cond_id ) a WHERE t.biosum_status_cd = 9 AND a.biosum_cond_id = t.biosum_cond_id

INSERT INTO cond_column_updates_work_table(biosum_cond_id, swd_vol_ac_grs_stem_ttl_ft3) 
SELECT DISTINCT(a.biosum_cond_id),a.ttl as swd_vol_ac_grs_stem_ttl_ft3 FROM tree t, 
(SELECT biosum_cond_id, SUM(voltsgrs * tpacurr) as ttl FROM tree 
WHERE spcd< 300 AND voltsgrs IS NOT NULL AND tpacurr IS NOT NULL AND statuscd = 1 AND dia >= 1 
GROUP BY biosum_cond_id ) a WHERE t.biosum_status_cd = 9 AND a.biosum_cond_id = t.biosum_cond_id

**Comment by jsfried** [comment]
Checked a random OR plot in a recent project- calcs are perfect
