### ISSUE TITLE
FVS: Update line FVSIn logic that sets ht and httopk to 0 for htcd 4

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#259]
//If Htcd not in {1,2,3} then set the Ht and HtTopK to 0
strSQL = Queries.FVS.FVSInput.TreeInit.DeleteHtAndHtTopKForNonMeasuredHeights(strTreeInitWorkTable);

**Comment by jsfried** [comment]
Might be better to just add a "4" into the list in case Htcd (and HT) are null for some reason ( so that we give FVS a chance to calculate ht if there is no height).

**Comment by lbross** [comment]
Use this query after linking master.tree to the fvs input database to validate fix:
SELECT htcd, FVS_TreeInit.ht as ht, HtTopK
FROM FVS_TreeInit INNER JOIN tree ON (FVS_TreeInit.Tree_ID = val(tree.fvs_tree_id)) 
AND (FVS_TreeInit.Stand_ID = tree.biosum_cond_id)
where htcd = 4

**Comment by jsfried** [comment]
The heights are coming into TREEINIT beautifully for htcd 4 cases.
