### ISSUE TITLE
DATABASE: Interface with new FCS .jar

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#262]
This issue tracks changes that need to be made to BioSum to properly interface with the new FCS .jar for calculating biomasses and volumes.

1. Replace  centroid_dia_ht_actual with centroid_dia_ht. We can send nulls as this is currently required only for PACI plots

**Comment by lbross** [comment]
From Jason:
We will need to add ecodiv to the biosum calc process.  This is for CRM2.
For now, we can use ecosubcd in its place.

**Comment by lbross** [comment]
Implement an error handling system. Jason suggests two tiers of errors:

1. System-level error codes; One per run. Examples: 0: No errors 1:  Sqlite tree database not found 2:  Sqlite tree config database not found 3:  Successful run with some tree errors etc.
2. Per tree errors could include: --No dia --No ht --Species config data not found for this tree --etc. These errors would be written back to the SQLite database. BioSum could read them from the database and write to the master.tree table or an error table that could be audited or queried.

**Comment by lbross** [comment]
Change references from biosum_volume to biosum_calc. The output table in the SQLite database will have a new name.

**Comment by lbross** [comment]
Need to add ecodiv to master.plot. Source is FIA plot.ecosubcd. Need to add stdorgcd to master.cond. This includes updating the scripts that create the tables for new projects and version_control for existing projects. Also need to update the plot load process to start loading these fields from FIA.

**Comment by lbross** [comment]
Record of switches that are available with v0.3.02
![image001](https://user-images.githubusercontent.com/11527966/153924964-13c8b0f2-6b54-454c-ab5c-9fb991964717.png)

**Comment by lbross** [comment]
Got an error in fcs_tree.db when using Tree Troubleshooter on master.tree table: No configuration found for the config/spcd combination. This was due to the trees having a null dia (bad input data). Jason says he will try to remember to separate those errors out when we need a new version. When we fully implement the new equations at the latest.

**Comment by jsfried** [comment]
Was this a manually input tree or one that came from FIADB? Strange that any tree that BioSum would try to process (live only, right?) would have a null dia.

**Comment by lbross** [comment]
This was in the master.tree table of Sebastian's FTCE_JaJoSi project. He loaded it using the old .jar so he probably wouldn't have seen the error. Looks like it came from FIADB because the fvs_tree_id didn't have the "S". I was using the Tree Troubleshooter so it may not have as many checks as regular processing.

**Comment by jsfried** [comment]
Troubleshooter interface now working great. For what it is worth, the results for the species I tested (Doug Fir and CA Juniper) don't seem to vary with the setting of DiaHtCd but it is good that we set it in case there are species in some region for which this setting does matter.
