### ISSUE TITLE
Consider no longer loading tree_regional_biomass

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#263]
The end of the load displays number of records loaded-- it shows zero for TreeRegionalBiomass and in fact that table in master is empty. Have we changed process so that we don't need that table? If so perhaps that line of the success dialog (and the table itself?) could be removed.

**Comment by lbross** [comment]
The biomass values that used to come from this table are now loaded using another process. This table is no longer needed. We should remove it from the plot input process. Jeremy's original error was due to not importing the tree_regional_biomass table into the input MS Access database.
