### ISSUE TITLE
Change default background color to make selected text visible

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#266]
The default highlight color (for selected text/rows) when BioSum is installed is royal blue. It is opaque and the user cannot read anything thus highlighted. While it is controllable via the Settings menu, it makes sense to choose a default color that is transparent. Sebastian and Jeremy suggest pink. 

![image](https://user-images.githubusercontent.com/17485472/144120820-f52a72cb-9b26-4865-9a99-312014ef57bb.png)

Priority is low, but seems like an easy fix and one that promotes usability (and one less thing to have to teach users to go fix in settings)

**Comment by lbross** [comment]
This is done. I changed the default background color to magenta which is the color indicated on the attached image. Pink is considerably lighter.
