### ISSUE TITLE
FVS: Update FVSIn creation from FIA2FVS to support multiple FIA databases

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#269]
Update the current process to make it an append vs an overwrite. The UI stays the same, but BioSum checks to see if there are existing FVSIn.db for the selected variant(s). If there is are existing FVSIn.db for the selected variant(s), it will give the analyst the option of appending or overwriting the existing files. This check will run once at the beginning for all selected variants so that the process can run unattended as it loops through the variants.

**Comment by sebbusby** [comment]
This function is working properly in BioSum 5.9, great addition!
