### ISSUE TITLE
DATABASE: Add Manage Tables functionality for SQLite tables

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#270]
We need a way for the analyst to look at SQLite tables without using MS Access/ODBC or SQLite Navigator as we migrate more BioSum tables to SQLite.

**Comment by lbross** [comment]
@jsfried requested some text on the manage tables screen indicating which folders might contain SQLite databases. Upon further reflection, it may be better to include this information on the help screen for this tool, which I have done. This way, if we don't get around to keeping some text on the screen up-to-date, it won't matter quite so much and it keeps the screen cleaner. If a person is confused that they aren't finding any SQLite tables, the obvious place to look is the help button.

**Comment by jsfried** [comment]
good point. suggestion accepted.

**Comment by sebbusby** [comment]
Working, looks good!
