### ISSUE TITLE
DATABASE: Condition cleaner not processing gis_travel_times.accdb

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#274]
The delete conditions script seems to be working on the wrong version of the gis_travel_times. BioSum left the accdb version of gis_travel_times apparently untouched.

Verified that the condition cleaner is only processing .mdb files in the gis\db folder. Updated this to include both .accdb and .mdb.

**Comment by jsfried** [comment]
works flawless!
