### ISSUE TITLE
DATABASE: Updates to Tree Troubleshooter

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#279]
1. For single tree calculations the dia is hard-coded to 5.09999990463257. This causes confusion with the dia that is sent for calculation doesn't match what is entered in the text box on the screen. I changed this so it now reads from the text box.
2. For single tree calculations diahtdcd is hard-coded to 1. I changed this to a combo box where 1 and 2 are the available values. 1 is the default.

**Comment by jsfried** [comment]
This now works great!
