### ISSUE TITLE
Implement new BioSum logo

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#280]
1. Attached is a BioSum logo that is part of a concept diagram that I worked with a graphic artist at PNW to produce. It would be nice if there were a home for it on the About BioSum dialog.
2. When I run BioSum, it shows as an uninspiring  white square icon on the task bar. Is there any way to make it show as something more distinctive? We may have raised this before but I can’t remember why we are in the situation we are in (with no control over how it displays on the task bar)
![biosum-logo-061622](https://user-images.githubusercontent.com/11527966/176243077-18d0b3a9-418d-4e0b-a2ab-0083f11727d1.jpg)

**Comment by lbross** [comment]
There are currently 2 logos on the About Biosum dialog. 1) PNW FIA and 2) The USFS shield. Would you like to add this as a third logo or replace one of the existing ones? I can also look to see if there is a way to use this as the image for the desktop shortcut for the application.

**Comment by jsfried** [comment]
I do think we want 3 logos but not the two that are there. I would replace the PNW FIA one (which was an unofficial glyph from 15 years ago that is no longer used or recognized by anyone) with the FIA Nation's Forest Census one at this web site:
https://skylightforestry.com/services/forest-inventory-and-analysis-fia/ or the attached
![FIA_logo](https://user-images.githubusercontent.com/17485472/176362193-b0eebf21-d4bb-4524-a4fb-c5998938c084.jpg)
and replace the shield with this shield (attached) which is cleaner:
![FS_logo](https://user-images.githubusercontent.com/17485472/176362708-26712e13-e6d4-4312-9c1a-e8027bded517.jpg)

Order, L to R, should be BioSum, FIA, USFS

Thanks!

**Comment by lbross** [comment]
This is what I currently have for the 'About' screen. The images aren't as clear as I would like. I think we lose something when I make them smaller to fit and then Visual Studio does something to them to present them in the PictureBox. The alternate FIA logo is in .webp format which Visual Studio can't consume. I asked my sister (a graphic designer) to convert it to .jpeg. Maybe it will be clearer than the current FIA logo?
![about_biosum_3](https://user-images.githubusercontent.com/11527966/176788806-52d026a8-24c7-40a6-bf58-0c5260f9db0f.jpg)

**Comment by jsfried** [comment]
Yes, those first two logos do degrade don't they? Perhaps the BioSum graphic is too busy for a logo. I've been trying to get hold of an FIA logo that is clearer but have had no success so far. It probably needs to be reworked in a graphics package-- beyond my capacity, unfortunately. And I don't have software that does that...

**Comment by lbross** [comment]
I just updated the screenshot because part of the BioSum logo was cut-off. I will ask my sister about the first 2 logos tomorrow. I am using MS Paint to reduce them. Maybe she has something that will do a better job.

**Comment by jsfried** [comment]
Probably requires some expensive Adobe product :-) Thank your sister for us!

**Comment by lbross** [comment]
I deployed the image in the application. The image is a .jpg. Microsoft only allows .ico files in most places in the application. I trimmed much of the whitespace off and used an online converter to generate an .ico file. I'm attaching a document with some sample screenshots. Honestly I don't think it looks great because it is too complex an image to be used as an icon. Also, I am not a graphic designer, but I think it would look better if the background were transparent rather than white. I don't know if your resource could change this?
The icon looks best in the desktop and menu shortcuts because it's a little larger there and you can read it. It would still look better with a transparent background. If we don't have a resource to make changes, my vote is to use it in the shortcuts, but not try to use it in the application.
With my sister's help, we do have the images on the about screen looking reasonably good. I will deploy that with the next release.

**Comment by lbross** [comment]
The smaller .ico file appears to work the best. I am attaching an updated .docx with some additional screen captures. Just a couple of more questions for you:

1. We have the original (complex) graphic as 1 of 3 images on the updated About Biosum screen. Keep or change to the simplified glyph?
2. I was able to use the original, complex graphic as the desktop shortcut and and in the Windows Start Menu. Keep or change to this simplified graphic? I thought I would like the older one, but when I look at the screenshots, the simplified one is growing on me. Plus, it might be nice to be consistent with the icon on the application which needs to be the simple one.

[icon_samples.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/9339112/icon_samples.docx)

**Comment by jsfried** [comment]
I am with you Lesley-- I love simplicity and consistency. Let's go simple all around.

**Comment by jsfried** [comment]
Desktop icon works, as does the About Biosum dialog. However, the icon showing in the taskbar is still generic (the one at the far right of this graphic:
![image](https://user-images.githubusercontent.com/17485472/195691026-f7f817d4-1ae0-4389-9db6-49c1c5ae849e.png)

**Comment by sebbusby** [comment]
BioSum Logo is working for me in 5.10 in various places (desktop shortcut, taskbar, in application). Close issue until further evidence is provided?

**Comment by jsfried** [comment]
The logo displays great on one of my computers. On the other, it does not display in the task bar, but I suspect this is due to other versions running on my computer and something I may have selected in the shortcut properties at one time. I am willing to live without the icon in my taskbar on this computer so will close the issue for now.
