### ISSUE TITLE
FVS: Update Sequence Number definition screen with reasonable default and options

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#282]
Set the initial (default) options for the 4 tables to match a pattern that we commonly recommend: 1-8-1 Treat Every Cycle
Add this option and 3 additional options to the 'Default SeqNum Options' pick list:

- 1-3-1 Treat Every Cycle
- 1-9-10-10-10 Treat First Cycle Only
- 1-4-5-5-5 Treat First Cycle Only

These options are defined in Appendix B of the FIA BIOSUM - Sequence Number Enhancements document.

**Comment by lbross** [comment]
To assign FFE templates the FVS_POTFIRE table needs to be selected from the list of tables. We realized that this creates a requirement for FVS_POTFIRE in projects that want to use FFE data. We do not want this. We will add an 'FFE' checkbox next to the template picklist to indicate that the FFE sequences should be applied to the selected tables.

**Comment by jsfried** [comment]
The options in the drop down look good!

**Comment by jsfried** [comment]
Multi-table assignment (via control click) works. One potential confusion point is that user may think checkbox for POTFIRE might apply to other FFE tables but it can't.

**Comment by lbross** [comment]
I'm not sure what you mean by 'checkbox for POTFIRE'. Are you talking about the Base Year checkbox? The only way I can think to reliably handle that is to not let POTFIRE be selected with any other tables (like STRCLASS) which removes some of the benefit of the multi-table assignment. But if you think the risk is too big, we can do that.

**Comment by lbross** [comment]
We will allay @jsfried concern with the Base Year checkbox by preventing FVS_POTFIRE from being selected with any other tables. It will work the same way as FVS_STRCLASS.

**Comment by sebbusby** [comment]
RE: "Add an FFE checkbox next to the sequence template pick list to support applying POTFIRE sequences to projects that don't have an FVS_POTFIRE table. Restrict FVS_POTFIRE to being assigned by itself because other tables cannot support BaseYr."

Appears to be working properly

**Comment by lbross** [comment]
From @jsfried:

> All the pick list options with BaseYr in their name don’t make sense for any table except for POTFIRE (the only one that baseyr can be implemented). I don’t think it makes any sense to have base yr options showing in the picklist for any table. Better to have only NoBY options (and then you don’t need to label them as NoBY). We can provide instructions for how to mod the Seqnums for a run that does use baseyear for the POTFIRE table.

Please update the 'Seqnums All' tab on the [TablesProps.xls](https://usfs.box.com/s/ptkovnk4eoicpyzc146ctii0u1bz6s9r) with your changes and I will implement them. 

> What does the list of packages in the packages field signify? Are these packages for which seqnum has been assigned or is it always a list of all packages because we now require that all packages use the same seqnum assignments? If packages were added to the project after seqnums were assigned, would those packages be missing from this list? Perhaps the field should be enlarged and/or be given a scroll bar

The read-only list of packages is always a list of all packages because we now require that all packages use the same seqnum assignments. There is code throughout FVSOut processing that needs the package because it supported sequence number by package. It is not a trivial task to remove this. I haven't decided if I'm going to remove it when transitioning FVSOut to read from SQLite.
If packages are added after seqnums were assigned, they would appear on this list because it is always the list of current packages. However, they wouldn't have sequence numbers assigned to them. The sequence number assignments need to be re-saved if new packages are added to update the configuration tables. This isn't ideal but it is lower risk than ripping out the rxpackage references in FVSOut. I believe we discussed adding it to the FVS documentation.

**Comment by jsfried** [comment]
Thanks for the explanation-will update tonight or tomorrow...
