### ISSUE TITLE
DATABASE: Consider renaming landclcd to cond_status_cd

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#286]
Need to evaluate where/how the fields are used in BioSum to determine scope. Landclcd is an artifact of legacy systems and is confusing for new users and those familiar with FIADB.

**Comment by lbross** [comment]
Landclcd is not used widely throughout BioSum. It is used when creating/populating the condition table and creating the FVSIn databases. Renaming it to cond_status_cd would not be difficult but does require version_control to update the field name in the master.mdb/cond table for existing projects. 
Cond_status_cd is used during the plot load process in work tables when calculating the adjustment factors. This would not change.
I uploaded a [document to box](https://usfs.box.com/s/wv57ar1owgt839rlmodium1mrfxaoh87) that describes the references to landclcd and the usage of cond_status_cd in the adjustment process. Holding on this for now because it is not critical path.

**Comment by sebbusby** [comment]
master.cond.landclcd field is correctly being renamed to cond_status_cd
