### ISSUE TITLE
Add warning when opening projects with an old version of BioSum

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#289]
Check application version and project version. If project is newer than application, pop a warning message asking if the user is sure they want to continue. Any response other than 'yes' will stop the project from opening.

**Comment by lbross** [comment]
This is done and will be in our next version. Note that it will only help going forward. There is no way to retroactively deploy this to older versions.

**Comment by jsfried** [comment]
So the next version won't open a project with a version LATER than the next  version and so on?

**Comment by lbross** [comment]
Right. This is as we discussed. But unfortunately we can't fix it retroactively for previous versions that are already in circulation. And it will open the project but it warns you first and you have to click 'yes'. I didn't want to make it a hard stop just in case.

**Comment by lbross** [comment]
@jsfried: Do you want to test this so we can close it? You need to try to open a v5.10.1 project with v5.11.0. Hopefully straightforward.

**Comment by jsfried** [comment]
Actually, it was the other way around (open a 5.11.0 project in 5.10.1), which generated an appropriate warning. Thanks!

**Comment by lbross** [comment]
It's been a long week already. Thank you!
