### ISSUE TITLE
PROCESSOR: Update usage of voltsgrs

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#296]
Some variants outside of PNW may not have voltsgrs calculated for Woodland Species by FICS. Processor uses voltsgrs to calculate "merch" sapling volume: voltsgrs * (saplingMerchAsPctOfTotalVol/100) * tpa

And when voltsgrs = 0: (drybiot/od_wgt)*tpa*(saplingMerchAsPctOfTotalVol/100)

How do we want to handle cases where voltsgrs is null?

**Comment by jsfried** [comment]
Actually, it is some VOLLOCGRPs (a Forest Service FIA construct, not FVS variants) don't yet calculate VOLTSGRS for woodland species (so it comes back as null from FICS, apparently). Seems easiest to just re-set it to 0, given that we have the alternate calculation in BioSum. We could even get radical and just say to heck with voltsgrs and we'll always calculate sapling volume from drybiot (for consistency). one less requirement and potential incompatibility-- sorry that I did not see it sooner-- sometimes I am just too dense (or distracted) to see the obvious

**Comment by lbross** [comment]
I suggest dumping voltsgrs and calculating this with drybiot for everyone. My concern is that if we are no longer requiring/auditing voltsgrs, we can never know for sure which equation BioSum is using for a particular stand unless we go back and look at the individual trees. As I understand it, this is not a precise calculation in any event. I will also need to update the FVS post-processing audit to no longer require voltsgrs.

**Comment by jsfried** [comment]
Agreed. Now we just need to make sure that there is always a drybiot (but perhaps we already trap for that)?

**Comment by lbross** [comment]
We do indeed require drybiot. It is in the FVS post-processing audit.

**Comment by lbross** [comment]
Updated Processor to no longer consume voltsgrs. Using alternative calculation with drybiot for "merch" sapling volume. Removed voltsgrs from Post processing audit.

**Comment by lbross** [comment]
From @jsfried: I would not say that I am extremely confident that they area correct for woodlands species on account of the fact that for woodland species, I believe that the volume equations are for the entirety of the tree, not the “merch” part  (because by definition, woodland species have no  merch parts). However, I have been able to duplicate the calculation for a condition with a single one seed juniper tree and can see that chip vol and chip biomass are getting calculated exactly as specified in the processor redesign objects. I am not 100% certain that the design is correct as my understanding of what, exactly, is in volume and biomass fields in FIADB has evolved and it is likely that we are double-counting the “non-merch” parts of the woodland species trees given that volcfnet holds, for woodland species, 

> “For woodland species (REF_SPECIES.WOODLAND = X), VOLCFNET is the net volume of wood and bark from the d.r.c. measurement point(s) to a 1.5-inch top diameter, including branches thatare at least 1.5 inches in diameter along the length of the branch.”

, 
so calculating biomass as a conversion of 60% of the volume, converted to biomass plus 40% of drybiot, can lead to anomalies (given that regional_drybiot, which is were we get our drybiot in BioSum currently, and volcfnet, are not directly connected or consistent). At the same time, I am seeing that regional_drybiot and drybio_wdland_spp are often very different from one another (even by a factor of two), which  doesn’t generate a lot of confidence in biomass estimates (which is what BioSum is all about!, or at least a lot of what it is about), but will defer dealing with this until the volume and biomass equation transition settles out. I would say that we are good to go for 5.10.1 though, based on having ascertained that we are no longer dependent on voltsgrs and are at least getting some biomass estimate in place and utilized in Processor.
