### ISSUE TITLE
FVS: Update Post-Append Audit to check for records in FVS_CutTree table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#297]
If sequence numbers are incorrectly configured, it results in an empty FVS_CutTree table which causes exceptions in the Processor tree species audit and calculations. We should add a first step to the Post-Append Audit (which is checking for valid Processor input) to check for records in FVS_CutTree. Some checks should also be added to the Processor modules to catch this case before throwing an exception, if the analyst doesn't run the audit before trying to run Processor.

**Comment by lbross** [comment]
Added validation to Post-Append audit, Tree Species audit, and Processor run tasks to check for records in FVS_CutTree before proceeding.

**Comment by jsfried** [comment]
The post-append audit works (when run on package 999 grow-only, it tells us that there are not cutlist records). However, it is unclear when this would come up in the tree species audit-- when there are NO packages that successfully generate cut list trees? Packages like grow only are already not showing up in the Processor package list so they can't be checked to run.

**Comment by lbross** [comment]
I believe this would come up when there are NO packages that successfully generate cut list trees. This was the case when Ryan encountered the error with his arizona_four_forests project. This use case would probably only happen when sequence numbers are bad. Using an old version of Ryan's project would test this contingency.

**Comment by jsfried** [comment]
Have tested an old 4fri project which has seqnums incorrectly loaded and thus no cutlist trees. Processor trapped for this.

**Comment by lbross** [comment]
From @sebbusby: I can confirm that specific piece of  #297 is fixed, It’s no longer giving me a hard-stop, just a warning to proceed.
