### ISSUE TITLE
DATABASE: Plot load fails with GRM option after October FIADB release

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#306]
The HT_BEGIN and HT_END are no longer in the tree_grm_component table. This causes a database error when BioSum tries to load plots if the GRM option is selected. HT_BEGIN is used to populate FVS_TREEINIT_COND.HTG. We need a temporary workaround so that analysts can load plots with the updated FIADB schema until a final solution is negotiated.

1. We will update the PLOT load sql so it doesn't try to load HT_BEGIN and HT_END. These fields will be left null
2. The GRM option will be hidden on the FVS In screen. The effect of this is that FVS_TREEINIT_COND.HTG and  FVS_TREEINIT_COND.DG will be populated with the values from FIA2FVS. These are the only two fields that come from GRM.

**Comment by lbross** [comment]
Additional updates are required for this interim solution:

1. Remove 'Use Growth, Removal, Mortality Data' checkbox and associated pick list from 2nd plot load screen. This should prevent loading of the GRM tables.
2. Re-label 'Growth Removal Mortality' groupbox to 'Calibration Data' on the FVSIn Options tab
3. Re-label 'Use GRM calibration data if available' to 'Use previous height' on the FVSIn Options tab
4. Add new checkbox labeled 'Use previous diameter' on the FVSIn Options tab
5. Both of these checkboxes are unchecked when the screen loads
6. If 'Use previous height' is not checked set HTG to null in FVS_TREEINIT_COND else leave FIA2FVS value in HTG field
7. If 'Use previous diameter' is not checked set DG to null in FVS_TREEINIT_COND else leave FIA2FVS value in DG field

Don't forget to update FIA2FVS_BIOSUM_FVSin_Mapping.xlsx when this is done.

**Comment by lbross** [comment]
A reminder that calibration data is no longer supported in the legacy FVSIn.accdb with these changes. That process was dependent on the GRM tables and doesn't have access to the FIA2FVS values. I know we don't use it anymore but I think it was used a while back for stands that weren't in FIA.

**Comment by lbross** [comment]
Updated requirements for item 5 above. Both of the calibration should be **checked** when the screen loads.

**Comment by sebbusby** [comment]
Validated, looks good
