### ISSUE TITLE
Start signing .msi with Forest Service Digicert certificate

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#308]
Option #1: Right-click on item to be signed and select DigiCert Click-to-sign
Option #2: Open a Powershell prompt in the folder containing the .msi and run the following command:
smctl sign --keypair-alias=KEYPAIR_ALIAS --input=fia_biosum_setup_vBeta5101.msi -v

When the .msi runs 'Forest Service' will show as verified publisher.
![image](https://github.com/USFS-PNW/Fia-Biosum-Manager/assets/11527966/f4155e3e-9614-45f5-b458-2baf58a2389b)

**Comment by jsfried** [comment]
@lbross: Congrats on getting it worknig. Sorry it had to be command line. For the uniitiated, how do you start up a powershell?

**Comment by lbross** [comment]
Option #1 actually works great, so no need for the command line. But the command line is more verbose so I wanted to record the syntax for troubleshooting purposes. To start-up a powershell, navigate to the folder containing the .msi. Then shift-right click, with nothing selected, and you'll see the option to 'Open Powershell Window Here'. I learned this today myself!

**Comment by jsfried** [comment]
Wonder of wonder, it installs without defender complaints!
