### ISSUE TITLE
FVS: Enter Pre/Post sequence numbers using text boxes instead of drop down control

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#31]
From @sloreno : When assigning sequence numbers, allow values to be typed in, rather than requiring the use of drop down menu. This is on the Define PRE/POST Table SeqNum screen (uc_fvs_output_prepost_seqnum).

**Comment by lbross** [comment]
Will check with @lpotts to see if there is a reason he used drop down controls instead of text box initially. Need to research existing validation on these values. For example, do they need to be sequential with no gaps?

**Comment by jsfried** [comment]
I have to believe that there is not too onerous way to validate user input short of mandating selection from lists. 25 years ago, when I was programing, there were error-trapped functions one could call (in Turbo Power Software add in for Turbo Pascal) that would only accept numeric input within a specified range (which could be specified using variables, not constants), and which had pre-edit and post-edit links into which you could insert additional validation functions. I have to believe that capacity for such validation has moved forward in a quarter century, not backward. At least I want to believe. Overuse of dropdown and pick lists as mandatory is tiring and frustrating to the user.

**Comment by lpotts** [comment]
You can use text as input. The combo boxes served to ensure only a value within a certain range could be selected.


-Larry

**Comment by sloreno** [comment]
In many of the modules that contain drop down menus for entering input, you
can enter text, but that is not the case with the Sequence Number input
referred to here.

**Comment by lbross** [comment]
@jsfried C# provides a multitude of options for validating the input. Since we are able to ask @lpotts for the history, it helps to make sure that there wasn't a compelling reason for the original implementation before changing things. 
@lpotts Thanks for the background. 
@sloreno We do have the option of making this an editable combo box rather than just a text box so you could either select a value from the list or enter your own value. Is that what you'd like to be able to do?

**Comment by lbross** [comment]
I found some settings for the comboBox control that support auto complete. With this approach you can type into the box and the list automatically scrolls to match what you type. It's similar to auto complete in a web browser search box. You are still restricted to the items on the list, which is desirable in this case to avoid invalid values, but you don't have to use the arrows to locate your selection.

I think this is a simple solution that will improve usability without having to write a bunch of validation code. Let me know if you think this will work. 

These are the settings I can change on each comboBox to implement the solution:
AutoCompleteMode: SuggestAppend
AutoCompleteSource: ListItems
DropDownStyle: DropDownList

**Comment by jsfried** [comment]
That sounds like an improvement.

Btw, is github updated with Sara’s new email address so that she gets messaged as needed?

**Comment by sloreno** [comment]
The proposed solution looks like a good one Lesley, just being able to type
in a number will be very helpful.

**Comment by lbross** [comment]
Changed settings on combo boxes. Found that you do have to click on the box to select your desired value. You can't just tab to the next one. This will be in the next release of BioSum. If it's still too hard to use, we can revisit.

**Comment by lbross** [comment]
Closing. @sloreno confirmed this is resolved in v5.7.6.
