### ISSUE TITLE
OPTIMIZER: Processing Sites screen changes

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#310]
1. Make psite type read-only. We don't want the analyst to update the psite type from this screen
2. Hide the Update psite types button since we no longer want to update psites

**Comment by druepdx** [comment]
These changes have been pushed to my fork and are ready for you to take a look at

**Comment by jsfried** [comment]
Agreed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by druepdx** [comment]
@lbross I pushed an update with the 'Use Default Values' button removed

**Comment by jsfried** [comment]
Evan Patrick found this behavior:
"Wood processing sites are not editable BUT an unhandled exception is thrown when any site is clicked on (even to select/deselect for inclusion). Link to error message: https://drive.google.com/file/d/1NgVEWnAeeI_txSdWEAtkooiIm1FHdxf9/view?usp=sharing"

**Comment by lbross** [comment]
@druepdx: Can you take a look at this error?

**Comment by druepdx** [comment]
Yes, I can look into it. I was able to select and deselect psites without error, but I can try to replicate the error.

**Comment by druepdx** [comment]
@lbross I'm still unable to recreate the error but I did notice something. In Evan's screenshot, that one button hidden behind the Select All button is still there. In the most recent version of my code, it isn't there. I wonder if the error goes away with the most recent version of the code

**Comment by lbross** [comment]
Let me take a look at my test computer which has the latest v5.11.0 installed and get back to you. It's possible Evan is running an older build because we gave Same access.

**Comment by lbross** [comment]
@jsfried: @druepdx is correct. That "ghost" button should not show up if Evan is running the .msi that we distributed on May 24. Can you check with him? The build date should be on the "About BioSum" screen. There will probably be another .msi coming this week, depending on how soon we get through the validations. But Evan should NOT be using anything older than May 24.

**Comment by lbross** [comment]
Confirmed that Evan had an old v5.11.0 .msi. He is installing the 5/24 build and will try again.

**Comment by lbross** [comment]
Validated by @jsfried
