### ISSUE TITLE
SETUP: New BioSum_Keywords.kcp for FVS to address SDI and SDIMax anomalies

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#312]
@sebbusby and Dan discovered that FVS misapplies SDI and SDIMax when there are large numbers of seedings/saplings in the input data. This results in unrealistic growth when the simulation runs. This issue can be resolved with directive(s) in the KCP file. @sebbusby will submit an updated  BioSum_Keywords.kcp to include with the next .msi.

Do we also want to update the POTFIRE_Keywords.kcp to keep the in sync?

**Comment by sebbusby** [comment]
@lbross Please find the updated BioSum_Keywords.kcp attached for the next .msi in Box/BioSumBox/Temp30Days/BioSum_Keywords_update_12-15-23.kcp

Didn't we abandon the POTFIRE_Keywords.kcp, or is it still required for using BaseYr with PotFire table? Either way, I don't think it needs any updates, should still work as intended.

**Comment by lbross** [comment]
After reviewing the deployment configuration, @sebbusby is correct. We are no longer distributing POTFIRE_Keywords.kcp in the application .msi. We have a copy of it stored in GitHub for future reference if needed. This new KCP file is staged and ready to be deployed with the next .msi.

**Comment by sebbusby** [comment]
@lbross @jsfried Did some mild trimming of the BaseYr_POTFIRE.kcp file Jeremy uploaded, please find attached for archiving.
[BioSum_Keywords_BaseYr_POTFIRE.kcp.txt](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/13716562/BioSum_Keywords_BaseYr_POTFIRE.kcp.txt)

**Comment by lbross** [comment]
OK. The modified POTFIRE script is tucked away in GitHub for safekeeping but is no longer distributed with the .msi to avoid confusion.

**Comment by lbross** [comment]
From Dan S.: I saw on the validation spreadsheet that issue #312 is still ongoing. I’ve attached the .kcp file to close out that issue here as well.
