### ISSUE TITLE
FVS: Allow editing Sequence number definitions with Assignments window open

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#32]
From @sloreno

**Comment by lbross** [comment]
Can you provide an example so I can see how this is currently working? I click the View Sequence Number Assignments button and it asks me to choose a database. I am working with the BM example. I've tried a couple of the FVS output databases but none of them work for me. Biosum says it can't find the table. Thanks.

**Comment by sloreno** [comment]
Try one of the databases found in project/fvs/db (PRE/POST).

**Comment by lbross** [comment]
Still unable to get this to work. Assume there is an association between the table name in the grid on the right and the database that I should choose. For example if FVS_SUMMARY is selected, I should choose PREPOST_FVS_SUMMARY.ACCDB database in project/fvs/db. When I do this, I get the error: FVS_SUMMARY not found. This also happens for FVS_CUTLIST, FVS_STRCLASS, FVS_POTFIRE.

**Comment by lbross** [comment]
The dialog expects the user to choose an FVS created output DBfile and not a BIOSUM created PREPOST DBfile. To see how it currently works, select something like FVS\DATA\CA\FVSOUT_CA_P001-100-100-100-100.mdb.

The dialog is intended to define the PRE POST records in the FVSOUT_CA_P001-100-100-100-100.mdb that will determine the records to move to the PREPOST DB files.

It is easy to allow the user to switch back and forth between the windows but the values in the assignments window may be dependent on edits to the sequence number definitions. More research needed...

**Comment by lbross** [comment]
Closing. The queries need to run again after the sequence numbers are defined so the window needs to be closed and reopened anyway.
