### ISSUE TITLE
PROCESSOR: Remove scenario_rx_harvest_method table from scenario_processor_rule_definitions.db

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#332]
There are references to this table in the CreateProcessorScenarioRuleDefinitionDbAndTables(), DeleteScenario(), and CreateScenarioRuleDefinitionTableLinks() methods that will need to be removed, but this table doesn't appear to be used in the Processor logic and screens. This can be validated by checking the scenario_processor_rule_definitions.db for a new project to make sure the table is no longer in the .db. And by successfully running a Processor scenario for this new project.

**Comment by lbross** [comment]
Note that we are not removing this unused table from legacy projects, but it will no longer appear in the Processor scenario rules definition database starting with v5.11.1.

**Comment by lbross** [comment]
@Cat-Ducat-USDA Responding to your note in the validation spreadsheet. Is it true that the scenario_rx_harvest_method exists in projects created with v5.11.1 or later? I'm looking at the old cwi_5.11.1validation and I don't see it. We didn't remove it from older projects, so you may still see it there.

**Comment by Cat-Ducat-USDA** [comment]
No sorry, not true! It was removed. I had been looking at an older project, but forgot to update the sheet.

**Comment by lbross** [comment]
Closing because @Cat-Ducat-USDA said it works
