### ISSUE TITLE
OPTIMIZER: Updates to Wood Processing Sites screen

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#333]
Develop a way to shorten/abbreviate the Site Type and Biomass Processing Type fields to reclaim some screen real estate. Add state and county columns. Make sure the state and county columns are sortable. This is for a post v5.11.0 release.

**Comment by druepdx** [comment]
Here are my proposed changes @jsfried:

Site Type:

- "Processing Site - Road Access Only" -> "Processing Site"
- "Railhead - Road To Rail Wood Transfer Point" -> "Railhead"
- "Rail Collector - PSite With Both Road And Rail Access" -> "Rail Collector"

Biomass Processing Type:

- "Merchantable - Logs Only" -> "Merchantable"
- "Chips - Chips Only" -> "Chips"
- "Both - Logs And Chips" -> "Both"
- "Other - Nongeneric Wood Facility with Potential" -> "Other"

We can then add the longer descriptions in the Help document

**Comment by jsfried** [comment]
Collectors and heads seem not obvious (they both collect wood but from different networks). Maybe:
Facility on Road
Intermodal xfer
Facility on Rail

all facilities on rail are also on road, so don't need to add road to the Facility on Rail title.

If need shorter, could do Facility, Intermodal, Facility/Rail

In a GIS we can have sites to calc travel times to but in a facility list we should have facilities, not sites (for example, 2 facilities, one for one type of wood and another for another, may share the same psite location).

Can shorten Merchantable to Merch if space needed

**Comment by druepdx** [comment]
Here is an example of a psite screen with the changes. I also changed the title of the Biomass Processing Type column to just "Processing Type" to shorten it
![image](https://github.com/user-attachments/assets/7c803ec6-14f1-4828-bfc1-3a643987fe8a)

**Comment by jsfried** [comment]
Looks great!

**Comment by druepdx** [comment]
@jsfried  Do you want to keep the Psite_Id in this screen or change it to the Psite_cn?

**Comment by jsfried** [comment]
You aren't going to like this, but I think we probably want both. The short number is easier to work with, but can change with a reload of psite data, right? whereas the CN is more stable. I know there is not a lot of room, so can we change Site Exists to Exists and Shorten from Yes to Y (and No to N)? And replace Site Type with KindCd entering the 1 digit value (and including a legend of codes in the gray area to the right of the Unselect all button? If that is just TOO much, and I have to choose 1, I would keep the psite ID as the longer number is too unwieldy to be useful if displayed on the screen, I think, @lbross @druepdx

**Comment by druepdx** [comment]
The psite ID is arbitrary and can change depending on what database is used to load the GIS data whereas the CN should be independent of input database.

After changing the Site Exists column to just Exist with Y and N values and compressing some of the other columns, I managed to get everything to fit. Let me know if the screenshot looks good.
![image](https://github.com/user-attachments/assets/0aa02c3a-27de-4d45-ba8d-35678b534ac8)

**Comment by jsfried** [comment]
Looks great! Thanks @USFS-PNW/developers
