### ISSUE TITLE
OPTIMIZER: Add psite_cn to processing_site table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#334]
This field will be null for legacy projects. After gis data is loaded, it will contain the psite_cn from the master travel times database. The psite_cn is a unique representation of the lat/lon of the psite so that the psite can be maintained over multiple iterations of the master travel times database. This will be a char field.

To validate, check the processing_site.psite_cn field after loading gis data. This should be in v5.11.1.

**Comment by druepdx** [comment]
This change has been pushed to my fork of the issue_344 branch. When gis data is loaded, it adds the psite_cn to the processing_site table in gis_travel_times.db.

**Comment by lbross** [comment]
We need to add something to version_control to add psite_cn to the psites table for existing projects. Otherwise if you try to load psites on an older project it will fail. You can use UpdateDatasources_5_11_0() as a model for a new UpdateDatasources_5_11_1() method. The psites table is in the dataSource infrastructure so you'll need to get the path to the table from there.  There is an example of this starting on line 7089 of version_control. 
I noticed that the biomass_cd 4 is in your branch already. We won't be able to to a pull request until this is supported (ignored) in the haul costs processing.

**Comment by druepdx** [comment]
From my understanding, adding the psite_cn to the existing table should be able to all take place in SQLite since UpdateDatasources_5_11_0 already copies the table over to SQLite. Is there a reason why it would be more complicated than that?

**Comment by lbross** [comment]
We need to add a method to version_control for database schema changes between v5.11.0 and v5.11.1. UpdateDatasources_5_11_0() will not run in this scenario because the project is already at v5.11.0. The act of adding the new field is definitely a SQLite function. But because the processing_sites table is defined in the DataSource infrastructure, we need to load and query the DataSource object so that we have the location to open a connection and add the column to the table.
Yes! The DataSource infrastructure makes tasks like this more complicated. It was before my time.

**Comment by druepdx** [comment]
I pushed code changes to my branch with an added UpdateDatasources_5_11_1() method. I did test it by just calling it in the PerformVersionCheck() method, but I removed that for now until the else if statement for when it should be called is added. I also commented out references to the biocd of 4 for now.

**Comment by lbross** [comment]
Nice job on UpdateDatasources_5_11_1(). You are correct that you need to stick it somewhere, temporarily, that will always be called. I will add it to the else if statement when we get closer to the actual release. I like how you check to see if the column is already there before trying to add it. I've learned the hard way that version_control needs to be able to run multiple times on a project without bombing.
Can we not just add a column to an existing SQLite table with the version of the .dll we're now using? I know that you have to create a temp table if you're dropping a column, but thought you could add one without doing that...

**Comment by druepdx** [comment]
I got so used to having to do things the difficult way that I didn't even think about that. I can change it to that super easily and push those changes.

**Comment by jsfried** [comment]
PSite_CN is added and populated
