### ISSUE TITLE
the draft gis_travel_times_master posted 8.16.2024 travel times table is missing psite ID for 774 California plots (46277 travel time records)

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#347]
Is this a Sam issue or a result of integrating Sam's data with the rest of the West? @druepdx

**Comment by druepdx** [comment]
Looks like this is an issue on Sam's side with the psite_ids of the travel cost csv he gave me for southern California. I'll reach out to him

**Comment by druepdx** [comment]
The issue should be fixed now and I uploaded an updated version of the database to Box

**Comment by lbross** [comment]
Closing. We are tracking the Western states travel times table under issue #324.
