### ISSUE TITLE
OPTIMIZER: RxPackage filter is no longer working as designed

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#351]
BioSum includes all packages in the output regardless of what is checked. This is fixed and ready to deployment. The SQL we were using stopped working after the conversion to SQLite.

**Comment by druepdx** [comment]
I fixed this in a prior push so it should be working in my fork

**Comment by lbross** [comment]
From @Cat-Ducat-USDA: Intentionally excluded packages are now excluded from output. Ran old cwi project version through optimizer, looked at new results tables that had only the two rxs I selected
