### ISSUE TITLE
OPTIMIZER: description field in optimizer calculated variable did not like use of a quote

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#353]
From @jsfried: I used an apostrophe in my description of a calculated variable and got an error message in calculating that made me think that punctuation is a no-no. It seemed to complete normally after the error though, but did not display the new variable in the list of calculated variables.  I went to remake it (and avoided punctuation) and it thew a dialog (OK the only choice) telling me that it was overriding existing calcs. So it must have been there but not visible. A little odd.

**Comment by lbross** [comment]
There are ways to get around this, but don't know that it's worth the effort to accommodate special characters in calculated variable names. Are you okay just supporting letters, numbers, and underscores? If so, we can add a filter to the textbox like we do with the additional harvest cost names.

**Comment by jsfried** [comment]
We can tell people not to use apostraphes or quotes but it does feel a bit like a straightjacket ;-)

**Comment by lbross** [comment]
There is a method in the SQLite data manager called FixString() that is intended to handle these cases. Hopefully this gives a good example on how we can fix this. Please check both the economic and fvs variable descriptions.

**Comment by druepdx** [comment]
Calculated variable descriptions should now allow apostrophes for FVS and ECON variables. It doesn't look like double quotations was ever an issue. I tested adding variable and recalculating them, and I just pushed my code changes

**Comment by lbross** [comment]
From @Cat-Ducat-USDA in the validation spreadsheet: I was not able to add " or ' to the description field for the calculated variables at all. @druepdx can you check with Cat and see why she can't use double or single quotes and you can? I don't want to close this if it's not working right.

**Comment by druepdx** [comment]
@Cat-Ducat-USDA I haven't been able to recreate any error when adding double or single quotes to the description of a calculated variable. Could you give me more info on what exactly is happening when you try to do this?

**Comment by Cat-Ducat-USDA** [comment]
@lbross Sorry I missed the mention yesterday! @druepdx  I vaguely remember that issue, but I am fairly certain that it was something I did, I have not had the issue since.

**Comment by lbross** [comment]
The let's close this bad boy!
