### ISSUE TITLE
Site index stopped showing up in BioSum generated FVSIn for Arizona 4FRI project when we switched from 5.10.0 to 5.10.1

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#365]

**Comment by jsfried** [comment]
Investigating the site index population for 4FRI I disovered that the current project version (built or upgraded to 5.10.1, not sure which) has no cases of site index populated in the BioSum generated FVSIn.DB. Could this be due to BioSum trying to override the FIADB.FVS_STANDINIT_COND value with a BioSum generated one (which could not be generated because we have never had site index roll-our-own capability for AZ)?  IN projects generated in 5.10.0, I am seeing FVSIn.DB.SITE INDEX populated but not in more recent versions. What would be helpful to provide or further test to get into this? We may need to go back to the very beginning of the 4FRI project to rerun FVS if there as not a site index populated for those runs that were written up in the Billion Ton report and reported at the SAF Convention.

**Comment by jsfried** [comment]
After investiating several versions of the project, it appears that the switch between having non null site index values to not having them may not have  been a BioSum version number switch-- I am seeing projects from 5.10.1 that have and don't have site index values. Reached out to Ryan to see if he has any ideas how this happened.

**Comment by jsfried** [comment]
Ryan has no ideas. I have successfully loaded a new project in 5.11.1 from the 4FRI area of interest and am getting site index populated for the same share of the conditions for which it was populated under 5.10.0 and 5.10.1 over a year ago. Ryan and Jeremy will meet this afternoon to see if we can come up with explanations for how the site index disappeared and if we reach conclusions, will reopen this issue and share here. For noiw, we are going to assume that it is unrelated to the issue of why site index is missing from many conditions in WA's CWI area of interest in the FIADB.FVS_STANDINIT_COND table.

**Comment by lbross** [comment]
My guess is that the FIADB source was missing the site index values for the projects that were built during a certain time. The logic for updating this from the BioSum side is pretty simple so it's probably not happening there. But yes, if it's missing from FIADB and we don't support it in BioSum legacy, the result would be null.
