### ISSUE TITLE
FVS: Use default values buttons on Treatment List screens 

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#53]
From @jsfried:
There is a button in the Rx component of the FVS module for “defaults” that, when clicked, replaces any Rxs that the user may have defined with 3 example ones. This behavior is a little disconcerting. A similar button in the Rx Package module seems to do nothing. It might be less confusing to remove both of these buttons—I am not sure what value they add at this point.

Affected screens: uc_rx_list.cs and uc_rs_package_list.cs.

**Comment by lbross** [comment]
The simplest course of action is to remove the 'Use Default Values' buttons from these screens. @jsfried  is correct; There is no code behind the button on the RxPackage screen. If there is any value in providing a list of default prescriptions for a new project, we could leave this button on the Rx Treatment List screen but add a warning that it will overwrite any existing Rxs. This warning would only pop if there are existing prescriptions.

**Comment by lbross** [comment]
For uc_rx_list.cs (Treatment List): Enable btnDefault only if there are no rows in lstRx. This will prevent the analyst from inadvertently overwriting their prescriptions but still provide the default option for new projects.

For uc_rx_package_list.cs: Delete the button. There is no code behind it.

**Comment by lbross** [comment]
Fixed uc_rx_list.cs. Will be in 5.7.7.

**Comment by tgm-pdx** [comment]
Still seeing Use Default buttons
