### ISSUE TITLE
PROCESSOR: Couple annoyances in Tree Diameter Groupings

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#55]
From @sloreno:
When assigning tree diameter groups in the Processor module (see window below)
a. It is hard to rejigger the thresholds, because you can’t assign a diameter greater than the next size class’s minimum. So say you had a size group 4.1 - 7 and another 7.1 - 10, and you wanted to change it to 4.1 – 8 and 8.1 to 11.  You would first have to delete the 7.1 – 10 group and the group above that.

b.When you create a group, then add another, the default is to set the minimum of the size class as the max of the previous one.  Could we change that to be the max + .1? The is not a valid combination of size classes.

![image001 2](https://cloud.githubusercontent.com/assets/11527966/19658825/576dab8e-99de-11e6-87ca-be519ee66b07.png)
Not sure if any of that makes sense. Of course these are very low priority, but may help with ease of use and user satisfaction.

**Comment by lbross** [comment]
Item A is a tough one to resolve so I'm not going to tackle it right away. Item B is an easy change. I have made the fix and it will be in the next BioSum release.

**Comment by lbross** [comment]
From @jsfried
It is not possible to delete dbh classes unless you delete all classes and start over (which has odd effects on wood values table).

**Comment by lbross** [comment]
From @jsfried 
We (josh and I) are entering 1 inch diameter classes, which due to the interface, is a bit vexing.  The decimal point is not deletable and one has to right arrow over it to put in the tenths piece in each case. Also, if anything high lighted then backspace has no effect. If you are entering five classes, it is a tolerable nuisance. When you are entering 30 classes it is pretty aggravating. Something for the bin list if/when we get time.

**Comment by lbross** [comment]
Consider an import function for larger numbers of classes. Classes would be in excel or .csv format. BioSum could process and assemble the classes rather than having to edit each one as its entered.

**Comment by jsfried** [comment]
This issue is now resolved and validated. Documentation in Chapter 5 (Processor) is also complete, as is the help screen, save for the need to edit one word -- the 2nd to the last word under item 4 of "Importing tree diameter groups from a text file " should be "diameter" not "species", so when that edit is made, this issue can be closed @lbross

**Comment by lbross** [comment]
The help has been updated and is staged for the next BioSum release. Closing.
