### ISSUE TITLE
DATABASE: Drop the frcs directory when creating new projects

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#57]
From @jsfried:
Can we drop the frcs directory for all future releases of BioSum (in terms of what gets created when you create a new project)? I don’t believe we store anything there. I am working on a figure for the user guide showing the directory structure for a BioSum project and am leaving that directory out of the lineup.

**Comment by lbross** [comment]
Changes made to uc_project.cs on master branch:

1. Stop creating FRCS directory when creating a project (lines 844 - 846)
2. Stop copying FRCS files to \\processor\\db (see lines 1143 - 1151)

**Comment by lbross** [comment]
Note: the current processor code creates the FRCS directory, if it is missing, when processor runs. This has been removed in the redesigned processor code.

**Comment by tgm-pdx** [comment]
Just checked on this. 5.7.6 is still creating a frcs excel file and frcs version file but no frcs directory.

**Comment by lbross** [comment]
@tgm-pdx: Can you check this again on v5.7.7? I just ran a couple of tests and am not seeing these files being created. These files are in the processor / db folder, right? Thanks!

**Comment by jsfried** [comment]
I concur. Not happening to me either. Tina, this would not remove these files from old projects, only prevent their creation in new ones.

**Comment by tgm-pdx** [comment]
I'll double check this tomorrow am and get back to you.

**Comment by tgm-pdx** [comment]
Just double checked this. Not seeing the files created for new projects.
