### ISSUE TITLE
FVS: Treatment dialog takes too long to run; switch to textbox

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#62]
From @jsfried:
It often happens that I inadvertently click “properties” on the FVS: treatment dialog, which initiates what can be several minutes of “not responding” as it works to pull together treatment info into a web page to display for me—there is no breaking out of it. A nice to have for this (some day), and perhaps reusable in some other situations where a mouse click will lock you up for minutes at a time, would be a “this will take some time—proceed?” yes/no dialog, to give me a chance to back out.

**Comment by lbross** [comment]
From @lpotts 
This is definitely something that needs to be fixed.  I did the PROCESSOR properties different because I did not like the time it took to load up the TREATMENT properties into an HTML page and then display it in a browser.  Displaying the PROCESSOR properties as formatted text in a windows dialog form was much faster.  Someone needs to redo the TREATMENT properties to formatted text instead of HTML.

**Comment by lbross** [comment]
Do we also want to make this change for the FVS Treatment Package properties?

**Comment by lbross** [comment]
Note: The current implementation has a section for associated FVS commands. Per issue #70, this tab is no longer available so I won't implement this in the text version of properties.

**Comment by jsfried** [comment]
Responding to lbross comment on FVS Treatment Package Properties:

Yes, assuming that it is also slow.

**Comment by lbross** [comment]
Thank you. Leaving issue open until it is implemented in code. It makes sense, I think, to have all the Properties work the same way.

**Comment by lbross** [comment]
Per @jsfried this issue has been validated in v5.7.9
