### ISSUE TITLE
PROCESSOR: Allow user to use harvest system from opcost_ideal

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#65]
The opcost_ideal table lists the lowest cost harvest system as determined by opcost. Allow user to select if they want to use the harvest system selected by opcost when running processor. Add a toggle to the run Processor screen? OpCost processing happens before tree vol val and harvest costs. If user desires, use harvest system selected by OpCost for harvest costs and tree_vol_val.

From @jsfried:
An architectural improvement would allow users to choose whether to extract harvest cost (and system) from the opcost_ideal table rather than the opcost_output table when desired. Since opcost runs before volval (I think), the resulting ideal harvest system could be used to characterize volval outputs (e.g., if opcost_ideal specified a CTL harvest system, then the vol val table would contain little chip volume because tops and limbs would have been left behind).

**Comment by lbross** [comment]
From @jsfried:
We’re going to need to have a way to snarf the results from the OpCost_Ideal table back into BioSum when the user chooses to run the processor with that assumption (by the way, I copied a processor scenario this weekend and it seemed to work—yay!). This would be in lieu of bringing in OpCost_output.  The piece of work that will be a little effort on your part when a user requests ideal system output in lieu of analyst specified harvest system output is to execute the volval table creation using the Ideal identified harvest system rather than the analyst specified one. Thus, different choices will be made about what makes it to the chip bin (because ideal systems generally don’t do whole tree logging).
 
A second enhancement will allow users to run a processor scenario (for either analyst specified harvest system or ideal) that will NOT incur chipping costs (so the chipping costs would be subtracted from the total harvest CPA) and not incur haul costs for chips and not generated chip wood mass and volume (or value). Analysts could specify per acre costs in these cases to account for disposal (generally via combustion) of these residues at the landing, if desired.
 
These additional options in processor will add tremendous value to users exploring the economics of different forest restoration options. Because core analysis sees the package as the fundamental unit of analysis wrt alternatives, users would need to make multiple copies of a package (with different package numbers) and run different variations of a package through processor with different choices about the “use ideal” and “leave chips” checkboxes (to be placed in the processor UI). Alternatively, they could leave the package specifications unchanged and simply run the same packages through different processor scenarios (with different status of these checkboxes or other choices) but since they will want to let core analysis consider all of the permutations, we would ultimately need a way to let core analysis consider the intersection of package and processor scenario, and that seems like a pretty huge revision. Multiple instances of the same RxPackage with different processor runs (would have to be all labeled as the same processor scenario though since only 1 scenario can currently be selected in core analysis, even though different packages would have been run through the scenario with different checkbox settings). Another option would be to move these checkboxes back to the RxPackage definition and Processor just follow whatever choices were made for the package.

**Comment by tgm-pdx** [comment]
@lbross is this addition represented by the 'lowest cost per acre' radio button in the Processor scenario window?

**Comment by lbross** [comment]
@tgm-pdx Yes. If you choose this option, you should see lower costs in the tree vol val table than if you don't. Assuming that you were not already using the lowest cost option either in the treatment or by selecting it in the Processor scenario window.
