### ISSUE TITLE
PROCESSOR: Run OpCost R script in background

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#72]
From @jsfried:
it would be really nice if BioSum would run happily and non-disruptively in the background; however, once the OpCost program runs, it pops on top and disappears my cursor until it completes. Could we make the pop-on-top behavior optional (e.g., for debugging  only)?

Check on options to run OpCost process in the background.

**Comment by lbross** [comment]
proc.StartInfo.CreateNoWindow = true;

**Comment by lbross** [comment]
Suppress OpCost window if debug level set lower than 3. Standard out and error both write to opcost_error_log.txt

**Comment by tgm-pdx** [comment]
@lbross or @jsfried Where do I specify the debug level to test this?

**Comment by lbross** [comment]
@tgm-pdx When you run BioSum one of the upper menu options is Settings. Click this and you'll get a settings form. The debug level is in the lower left-hand corner. I also commented on your question about the help but I didn't tag your login so I'm not sure if you got an email.
