### ISSUE TITLE
PROCESSOR: Adjust opcost inputs according to harvest system

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#75]
Some harvest systems require minimum values for yarding distance, TPA, and volume. See attached matrix. BioSum will adjust these values before sending input to OpCost according to the selected harvest system. The actual values will be recorded in the opcost_input file for audit purposes. Also, a flag will be added to the harvest_costs file indicating that adjustments were applied.
[Pre_adjustement_limits.xlsx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/828573/Pre_adjustement_limits.xlsx)

**Comment by lbross** [comment]
tpa adjustments should only be applied if tpa > 0 to start with

**Comment by jsfried** [comment]
Code works as designed. There are no longer any cases of zero density with non-zero TPA.
