### ISSUE TITLE
DATABASE: Remove fvs_species and fvs_common_name from tree_species table

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#79]
Determined that this column is not used from the tree_species table and therefore extraneous. Additional research needed to confirm that it is not used in the application. Also it will need to be removed from uc_processor_tree_spc.cs.

**Comment by lbross** [comment]
Looking at code to see if this column is used.
Confirmed column not used in site index processing; Fvs_tree_species used instead to translate.
It IS used in fvs_input.CreateFVS() to load up the spcd conversion table into an array; Could we use fvs_tree_species instead?
It IS used in uc_processor_tree_spc.cs.loadValues on grid. Do we just remove this column or pull it from somewhere else?

**Comment by lbross** [comment]
Continuing research:
This is a field on uc_processor_tree_spc_edit.cs. Do we remove from form since this field will no longer be maintained in tree_species table?

**Comment by jsfried** [comment]
Looks good. The only unfortunate thing is that the file on the C drive (containing FVS_TREE_SPECIES) is an ACCDB whereas the ref_master is an MDB. This prevents me from establishing a link to the FVS_TREE_SPECIES table which is sometimes handy for looking up the species info (common name etc.) that FVS considers goes with its species code for that variant. For analysts like me, who link up databases all the time, having a mix of ACCDB and MDB databases in a BioSum project is an ongoing barrier (since from within an accdb you can't link to a table in an mdb).

**Comment by sorgtyler** [comment]
I use the FVS species name for the FVS_TreeInit mist_cl_cd-related damage codes. I might be able to use the species codes instead, but I thought I should voice that now.

**Comment by sorgtyler** [comment]
I looked into it further and found that the Site Index/Site Species logic also uses the fvs_species column.

**Comment by lbross** [comment]
@lpotts: Please share your thoughts on switching biosum_ref.accdb to an .mdb. We discussed this during the design phase and chose .accdb because it was a more recent database architecture. Switching to an .mdb wouldn't be a significant effort, if we do it soon, since we've just started using this new .accdb.

@sorgtyler: You should be able to get what you need using a combination of the tree_species and fvs_tree_species table. The Site Index logic was updated to accommodate this change but you can't see it yet because I haven't merged my pull request. Hopefully soon! In the meantime, I'll send you an updated copy of fvs_input.cs so you can see how I accommodated the move of this field.

**Comment by sorgtyler** [comment]
I'm wondering if the current version of BioSum still refers to the ref_master.tree_species.fvs_species column in fvs_input.createSLF() and the fvs_input.site_index class. For example, does this code handle the new schema?

```
this.m_ado.m_strSQL = "SELECT spcd,fvs_input_spcd,fvs_species " + 
					"FROM " + this.m_strTreeSpcTable + " " + 
					"WHERE trim(ucase(fvs_variant)) = '" + this.m_strVariant.Trim() + "';";
				this.m_ado.SqlQueryReader(this.m_ado.m_OleDbConnection,this.m_ado.m_strSQL);
```

**Comment by lbross** [comment]
@sorgtyler: Sure. The code you cited no longer refers to the ref_master.tree_species.fvs_species. We use tree_species.fvs_variant and tree_species.fvs_input_spcd to look up fvs_tree_species.fvs_species, like so:

```
SELECT t.spcd,t.fvs_input_spcd,f.fvs_species
FROM tree_species t, fvs_tree_species f 
WHERE t.fvs_input_spcd = f.spcd
AND t.fvs_variant = f.fvs_variant
AND trim(ucase(t.fvs_variant)) = 'BM';
```
