### ISSUE TITLE
PROCESSOR: Rename TREE_SPECIES_GROUPS, TREE_DIAM_GROUPS in next release of version_control.cs

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#93]
Per issue #44 we are moving the tree species and tree diameter groups into scenario-specific tables in v5.7.9. In version_control for 5.7.9 we migrated these groups from the old to the new tables. We hoped to rename the old tables so analysts would know they are no longer in use. However, the dao object locked these tables. This is a cleanup task for v5.7.10.

Use this SQL to get the paths for all the tables:
string strScenarioMdb = frmMain.g_oFrmMain.frmProject.uc_project1.txtRootDirectory.Text.Trim() + "\\processor\\db\\scenario_processor_rule_definitions.mdb"
SELECT * FROM scenario_datasource where table_type in ("TREE DIAMETER GROUPS","TREE SPECIES GROUPS")

Code sample for renaming the tables:
            string strFormat = "MMddyyyy";
            string strSuffix = "_ver_control_" + DateTime.Now.ToString(strFormat);
            dao_data_access oDao = new dao_data_access();
            foreach (string strKey in dictTablesToRename.Keys)
            {
                oDao.RenameTable(strKey, dictTablesToRename[strKey], dictTablesToRename[strKey] + strSuffix, false);
            }

After tables have been renamed, delete the entries from scenario_datasource

**Comment by lbross** [comment]
This is ready for the initial release of 5.7.10

**Comment by jsfried** [comment]
Works!
