### ISSUE TITLE
CORE: BioSum crashes when you switch scenarios

### ISSUE THREAD

**Issue by lbross** [USFS-PNW/Fia-Biosum-Manager#98]
From @jsfried:
I am finding that with both processor and core, when I finish running a scenario, then open a new scenario (without first exiting BioSum), I get a fatal error. Then a continue/quit dialog.
I would say this happens 80% of the time when I switch scenarios in core, and somewhat less frequently when I switch scenarios in processor. It is annoying, but then I do have the workaround of restarting BioSum when this happens...

I do close the scenario before opening a new one.

**Comment by lbross** [comment]
I have pinpointed the error but do not know how to fix it. This is caused by a 'Too many client tasks' Dao error. Here is the stacktrace:
   at Microsoft.Office.Interop.Access.Dao.DBEngineClass.CreateWorkspace(String Name, String UserName, String Password, Object UseType)
   at FIA_Biosum_Manager.dao_data_access..ctor() in C:\workspace\BioSum\Fia-Biosum-Manager\src\dao_data_access.cs:line 37
   at FIA_Biosum_Manager.Datasource.populate_datasource_array() in C:\workspace\BioSum\Fia-Biosum-Manager\src\datasource.cs:line 261

The list of functions that are called going into this:
datasource.CreateMDBAndTableDataSourceLinks()
LoadDatasources()		}
LoadLimitedDatasources()
datasource.populate_datasource_array()

The fatal error occurs in datasource.CreateMDBAndTableDataSourceLinks()
on this line: 
					if (this.m_strDataSource[x,TABLESTATUS].Trim().ToUpper()=="F" &&
						  this.m_strDataSource[x,FILESTATUS].Trim().ToUpper()=="F")
Because FILESTATUS is null

We can check for null to avoid the fatal error but I think BioSum needs this info to access the table and continue processing.

**Comment by lbross** [comment]
Although we haven't tracked down the cause of the dao error, I updated the code in Queries and Datasource to lessen the impact on the user. We now check to see if an error occurred in LoadLimitedDatasources() and abend processing if it did. If by some chance, processing does continue, I added some checks for null values in datasource.CreateMDBAndTableDataSourceLinks() to avoid an unhandled exception (crash). This will be in the next BioSum release.

**Comment by jsfried** [comment]
In testing, I happened to click on Case Study button when I already had a scenario specification open and active and it allowed me to open a second case study scenario specification. It even let me run the two scenarios simultaneously, albeit slowly and with weird visual errors in the progress bars (missing or incomplete). However, one of the runs crashed (with an SQL message that I inadvertently cleared with an errant keypress) and the other completed successfully. While I can see how it would be useful to have two scenarios open at the same time (when comparing underlying assumptions, for example), I think it would be good to prevent someone from trying to execute two or more scenarios at the same time.

I am unable to reproduce the error that I was experiencing before (the exception error) when switching to a new scenario after running another scenario. Yay!
